from enum import StrEnum


class LetterStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    SENT = "SENT"


DEFAULT_QUESTIONS = [
    "📸 Photo Wall",
    "🌤️ One Good Thing",
    "💭 On Your Mind",
    "👀 Check it Out",
]
QUESTION_BANK = [
    "What's a moment in your life that felt like a crossroads?",
    "If you could alter one decision you made in your early 20s, what would it be?",
    "Have societal or familial expectations ever led you to a career decision that you wouldn't have made on your own? How do you feel about that decision now?",
    "Think of one of your big, lofty goals. What small step could you take today towards achieving it?",
    "What are people surprised to learn you're really good at?",
    "What word describes your essence the best?",
    "What is something other people admire about you?",
    "Who's life do you think you've impacted the most?",
    "Are there any relationships in your life that feel imbalanced? What would it look like to restore balance?",
    "What was a pivotal moment in your career that led you to where you are now?",
    "What was your favorite childhood toy?",
    "Are you settling for less than what you are worth? If so, why?",
    "What's something you recently came across that gave you hope or inspiration?",
    "What’s your biggest flex in life right now?",
    "What's a book or podcast you'd recommend that’s related to your career?",
    "If you could learn one secret from anyone, who would it be and what would it pertain to?",
    "What fact about yourself took you the longest to understand or accept?",
    "What thoughts distract you when you’re trying to get to sleep?",
    "How well do you feel your work aligns with your purpose or identity?",
    "What's an ethical dilemma that keeps you up at night?",
    "Who here is most likely to own 20 house plants and give each of them unique names?",
    "What do you think people might envy you for?",
    "Think of your biggest regret. If you could go back in time and make a decision to keep it from happening, would you?",
    "What legacy do you hope to leave as a result of your professional work?",
    "How's your family doing?",
    "What is the most powerful habit, good or bad, in your life right now?",
    "What's your philosophy in life?",
    "What's an interesting conversation you recently had?",
    "If you could change one thing about yourself physically, what would you change?",
    "What kind of person do you want to be?",
    "If every time you snapped your fingers, you would instantly and irreversibly be transported to a random point in humanity's timeline, would you snap your fingers? If so, how often?",
    "How do you feel about your relationship with your mother?",
    "What's the most significant risk you've ever taken, and how did it turn out?",
    "What area in your life are you looking to improve?",
    "What outfit makes you feel powerful, smart, or capable?",
    "What's the most challenging thing you're working through these days?",
    "What's a goal you're working towards?",
    "What's your favorite personality or character trait about yourself?",
    "How do you stay updated with the latest developments in your field?",
    "How has your industry changed since you started your career?",
    "What's the best career advice you've ever received?",
    "What's a hobby you've always wanted to try?",
    "What’s your strategy for professional growth?",
    "If you could live in any movie universe for a week, which one would you pick?",
    "What fictional character do you most relate to?",
    "If you only had one year left to live, what would you do?",
    "What's a fear you've faced and overcome?",
    "What's something you're embarrassed to admit you enjoy?",
    "What practice or habit (if anything) best supports your mental health/well-being?",
    "What does 'living authentically' mean to you, and how do you practice it in your daily life?",
    'Do you feel like you\'ve found "your people" yet in life?',
    "You can know when you die or how you die. Which do you choose?",
    "What’s a new movie or show you've enjoyed recently?",
    "What gives you supreme joy right now?",
    "What can you be kinder towards yourself for right now?",
    "What's the best advice you've ever given someone?",
    "What’s one family tradition you want to pass down to your kids?",
    "Can you share an instance where your first impression of someone was completely wrong?",
    "Is there a particular event or moment that redirected the course of your life? How did it impact you?",
    "Is there an experience you think everyone should have at least once in their lives?",
    "What’s your best tip for staying focused and productive?",
    "Who in your life always makes you laugh?",
    "Who is your favorite philosopher or thinker, and what influence have they had on you?",
    "What’s something at the top of your to-do list?",
    "In what ways do you mentor or support others in your field?",
    "What makes you optimistic about the future?",
    "If you could instantly bankrupt any person, company, country, or organization, who would it be?",
    "When was the last time you experienced stillness and wonder?",
    "If you could level up any aspect of yourself (i.e., strength, intelligence, charisma, etc.) but you had to decrease another aspect of yourself by the same amount, what aspects would you level up and sacrifice?",
    "What's the most important life lesson you've learned in the last 10 years?",
    "What would you title your memoir?",
    "How did you spend your most recent weekend?",
    "How’s your heart today?",
    "Who here is would most likely live the longest?",
    "What's a habit you're trying to develop or break?",
    "Have you ever desired or longed for something, but once you got it, discovered it was overrated or that you no longer wanted it?",
    "Which superpower would you pick to subtly make your everyday life easier?",
    "What's currently worrying you?",
    "What are you most proud of right now?",
    "How do you measure the impact of your work on society?",
    "If you had one minute left to live, what would you do?",
    "Have you ever turned down an opportunity, then came to later regret that decision?",
    "Can you share an unexpected goal you have for this year?",
    "What's a habit you'd like to adopt, but find difficult to stick to?",
    "How has your definition of happiness changed as you've gotten older?",
    "After death, you can roam the universe and observe anything you want for all eternity, but never interact with anyone or anything. Or, you can cease to exist. Which would you choose?",
    "What song has been on repeat for you lately? Does it have any special meaning?",
    "If your life was a genre of music, what would it be?",
    "What was your worst conflict with a partner and what happened? What'd you learn from the experience?",
    "A highly advanced alien species has arrived on Earth, and you are selected as the spokesperson to represent humanity. You have one sentence to communicate your most important message. What do you say?",
    "How do you feel about your relationship with your father?",
    "What's a standout moment where you felt excited recently?",
    "Imagine you could bring drawings to life; what’s the first thing you would draw?",
    "How do you balance work and personal life?",
    "What's a recent personal growth moment you've experienced?",
    "In what ways are you similar to your parents? In what ways are you different?",
    "What's a challenge you've overcome that made you a stronger person?",
    "What's your favorite smell?",
    "What has surprised you recently?",
    "How do you prioritize your tasks when everything seems urgent?",
    "What do you think is your biggest strength and your biggest weakness?",
    "What's your favorite article of clothing you own?",
    "What talent of yours do you consider to be inherent, like an advantage you were born with?",
    "What compliment would you give yourself right now?",
    "What public figure has had greatest impact on your personal life philosophy?",
    "What are 3 things you love about yourself?",
    "Explain your job to a 3 year old.",
    "What do you most need to hear right now, and from whom?",
    "Who in your life do feel is receptive to receiving feedback?",
    "What battles are you fighting right now?",
    "Would you rather have the power to turn invisible or to read minds?",
    "Which relationship in your life do you currently find the most challenging? What are you learning from it?",
    "What's one interesting thing you've been thinking about lately?",
    'What\'s a "red flag" in a relationship or friendship?',
    "What is the last book you read? Would you recommend it?",
    "How authentically do you feel you represent yourself to others?",
    "How has your perspective on the world changed in the last five years?",
    "What do people think is hard but actually isnt?",
    "Are human desires endless, and can a society exist without wanting more?",
    "What's one thing you miss the most growing up as a kid?",
    "What are you most grateful for in your life right now?",
    "Which relationships have become more meaningful to you as of late?",
    "The world needs more of my...",
    "If you could change one thing about your childhood, what would it be?",
    "What's something you currently doubt, conciously or subconsciously, that you can do?",
    "What advice would you give to your teenage self?",
    "What's your go-to productivity hack?",
    "What's the best relationship advice you've ever received?",
    "What areas of personal development do you feel you need to focus on to to achieve further professional success?",
    "What's your favorite snack?",
    "How do you reconcile the pursuit of your personal goals with the need to contribute to the community?",
    "You will be granted supernatural ability in one of your five sense (sight, smell, taste, hearing). Which would you choose, and why?",
    "Who do you wish was still alive? Could be someone you've met, never met, anyone.",
    "What advice do you wish you'd received earlier?",
    "Do you believe in second chances?",
    "What scientific or technological advance blows your mind?",
    "How do you approach your overall wellness?",
    "When was the last time you cried and why?",
    "Imagine you woke up with the ability to speak every language fluently; how would you use this power first?",
    "What's the most memorable dream or nightmare you've ever had?",
    "What do you wish people would stop talking about right now?",
    "Do you have a best year of your life? A worst?",
    "When do you feel most helpful to others?",
    "What is one commitment you've made to showing up differently in a particular relationship of yours?",
    "If you could use a time machine, would you rather have one that only goes back in time or only goes forward?",
    "If you could pick up a new skill in an instant, what would it be?",
    "Is there a behavior or pattern you keep falling into that hurts yourself?",
    "What's your favorite quote and why?",
    "Where do you wish you had grown up?",
    "What's one thing that you wish would never happen to you?",
    "What's the most significant risk you've taken in your career, and how did it turn out?",
    "If you could witness any event in the future, what would you choose to see?",
    "What's something from your childhood that you think no one else could relate to?",
    "Have you ever made a dramatic career shift, and what drove that decision?",
    "What's something you're you proud of, but never have an excuse to talk about?",
    "Is there anyone close in your life that perceives you differently than you perceive yourself?",
    "When do you feel most like yourself?",
    "What title would you give to the current phase of your life?",
    "What's a skill you use at work that you also use in your personal life?",
    "How would you summarize your life so far in one sentence?",
    "What do you think happens after we die, if anything?",
    "If the last month were a chapter of your life, what would you title it?",
    "Who has had the most positive impact on your life?",
    "What's something you used to be ashamed of but have come to embrace?",
    "What does love mean to you?",
    "What's a major life decision you made that you're really happy about?",
    "What do you consider as red flags in a potential employee or coworker?",
    "What do you wish you had done differently in the last month?",
    "What recent mistake taught you the most?",
    "Have you been to any cool places lately?",
    "What’s one of your earliest memories of earning money?",
    "What was your first job, and what did it teach you?",
    "What's something good that recently happened to you?",
    "How can you create an environment that will naturally bring about your currently desired change?",
    "What's an unpopular or controversial opinion that you hold?",
    "Have any priorities recently shifted to the forefront of your life?",
    "What is the most ordinary-seeming thing that you find fascinating?",
    "What are some bad things you did as a teenager?",
    "How has your perspective on work-life balance evolved over the years, and what influences shaped this?",
    "What does your ideal/dream life look like?",
    "What's going well with work or school? What's not going well?",
    "What's one thing you do to distract yourself that you think you should less of?",
    "Is there anyone you envy? If so, whom and for what?",
    "Are you currently mentoring anyone, or being mentored? How is that going?",
    "What do you have up in your browser tabs right now?",
    "Who here is is most likely to eat cat food?",
    "Imagine you could instill one habit in your child that they would carry for life. What habit would you choose and why?",
    "Has your gut feeling or intuition about someone or something ever been wrong?",
    "What's a common piece of advice you disagree with, and why?",
    "Are you currently holding a grudge against anyone?",
    "What self-limiting beliefs do you currently hold?",
    "What's something you wish you knew earlier about being a good partner?",
    "If you were an inanimate object, what would you be and why?",
    "What's something you've been reminding yourself to think, do, or feel lately?",
    "What are you most afraid of about yourself?",
    "What's something people often incorrectly assume about you?",
    "What's a deep question you often ask yourself?",
    "What's a recent decision you're glad you made?",
    "How do you resolve conflict with the closest people in your life?",
    "Is there anything you'd like to get off your chest?",
    "What do you think is the best place or way to meet a signifcant other?",
    "What is the single most critical issue you would want your child to be passionate about addressing in their lifetime?",
    "What's the most useful thing you've ever been taught in school?",
    "What character trait instantly makes you respect someone?",
    "Do you have an inner monologue? Do you think your thoughts in words or concepts?",
    "What's your favorite way to relax these days?",
    "What inaction or missed opportunity do you regret?",
    "What is the greatest physical pain you've ever felt?",
    "Who had the most significant impact on your career and why?",
    "On a scale of 1 to 10, how valued do you feel at work?",
    "How has your perspective on your career changed over time?",
    "What would brighten your day today?",
    "Who here is most likely to invent the next technology that'll save the planet?",
    "Is there any aspect of your identity you sometimes feel you must suppress or amplify in certain social settings?",
    "Where were you born?",
    "What's your least favorite part of your job and why?",
    "If you accomplished something major, who is the first person you'd tell and how do you think they'd react?",
    "Who here is most likely become a philanthropist?",
    "What's the most challenging ethical dilemma you've faced in your career?",
    "What is one thing you're tired of explaining to people?",
    "Which societal norm would you like to see ended, and why? What changes would you propose?",
    "What do you think is the most significant impact individuals can make in the world today?",
    "What's a common myth about your profession that you can debunk?",
    "What's one thing you would change that's commonly taught to children today?",
    "Think of someone you're currently in conflict with. If it was the last conversation you'd ever have with them, what would you say?",
    "If you had to give a TED Talk without any preparation, what topic would you choose?",
    "Is there anyone who intimidates you? Why do you think this is?",
    "Given the choice of anyone in the world, whom would you want as a dinner guest?",
    "Do you feel challenged enough at work?",
    "Are you closer to one of your parents than the other, and why?",
    "What's your favorite non valuable item you'll keep to the grave?",
    "What's a fear or insecurity you're working through?",
    "What's a time when you were extremely underprepared for the task or situation at hand?",
    "What's a funny or embarrassing moment you’ve had at work?",
    'What was your "rock bottom"? How did it happen, and how did you get out of it?',
    "Before having a conversation with someone, do you ever rehearse what you are going to say? Why",
    "What's something you admire about each person here?",
    "How do you prioritize your goals and desires in life?",
    "What's one way in which you're completely different from yourself 10 years ago?",
    "What is your why? What gets you up in the morning?",
    "What do you find yourself fantasizing about these days?",
    "What's something you recently taught yourself?",
    "What are you working on in your relationships (with friends or with a partner) right now?",
    "If you had $1M, but couldn’t spend a penny of it on yourself, what would you spend it on?",
    "What's a habit you picked up as a child that you wish you hadn't?",
    "If you were to suddenly inexplicably go missing, who in your life would be most likely to solve the mystery and find you?",
    "How well do you receive feedback?",
    "If you had the power to talk to animals, which species would you chat with first?",
    "You can guarantee that your child will have a deep understanding of one event in history. Which event do you choose and why?",
    "Do you have an internal hunch about how you will die?",
    "What fictional character would you most like to have as a mentor?",
    "In what ways do you think hardship can contribute to personal growth?",
    "What's a great piece of advice you recently received? Who was it from?",
    "What is something you never thought you'd be able to do, until you actually did it?",
    "What's something you're looking forward to in the coming months?",
    "What social behaviors of yours are driven by the need for safety, belonging, acceptance, or validation, rather than genuine desire?",
    "What's a surprising hobby you enjoy?",
    "What activity absorbs you completely and makes you lose track of time?",
    "You get to invent something. What is it and what does it do?",
    "Who here is would most likely become a CEO at a company ranked amongst the top 100 largest in the world?",
    "If you could be invisible, but it would mean being permanently invisible, would you want to be this way?",
    "What is the most important quality you look for in a friend?",
    "What color describes your mood today?",
    "Who here is is most likely to read every book in a school library?",
    "Do you love yourself? What does that look like?",
    "What's a new hobby or activity you've tried recently?",
    "What's the weirdest food combination you actually enjoy?",
    "Have you tried any new foods or restaurants lately?",
    "Have any failures played a significant role in your your career development?",
    "What's something you recently learned?",
    "What is the most fun you have had recently?",
    "What was your first job ever?",
    "What's a truth you've recently come to terms with?",
    "What's one of your biggest pet peeves?",
    "In what way do you differ most from your best friend? In what way are you most similar?",
    "Is there a quote or saying you call to mind often, intentionally or unintentionally?",
    "What's a recent moment in which you feel you represented yourself authentically?",
    "If you could go back and relive one day in your life without changing anything about it, which day would you choose?",
    "What's something you wish people asked you about more often?",
    "What is something you're terrible at but wish you could do well?",
    "What's a situation that tested your resilience?",
    "Is there anything important you've been putting off? If so, why?",
    "Have you attended any interesting work-related seminars or workshops lately?",
    "What is the dumbest but most innocent thing you believed as a child?",
    "What are you most jealous of about others?",
    "When was the last time you had a difficult conversation? Who was it with, and how did it go?",
    "Who has made a positive difference in your life recently?",
    "What's a movie you can watch over and over without ever getting tired of?",
    "Imagine that you can choose when and how you die. How long would you like to live, and how would you like to go?",
    "If you could erase one thing or event from your memory, what would you choose?",
    "You can stop time for 24 hours. What do you do with this opportunity?",
    "You can only guarantee your child learns one life principle. What do you teach them?",
    "A stranger is inhabiting your body for the day. What are some tips you’d give them?",
    "You're offered vast wealth, extraordinary intellect, renowned fame, or stunning looks. Which do you choose?",
    "What character traits do you most appreciate in your teammates?",
    "Some historical figures have epithets attached to their names (e.g. Alexandar The Great, or Michael Jackson: King of Pop). What would you like yours to be?",
    "How is your current health, fitness, or wellness routine going?",
    "What's your favorite memory in your childhood home?",
    'What would make you feel like "you made it"?',
    "If you could have witnessed one event from your family history, what would it be?",
    "What embarrassing memory will forever be seared in your memory?",
    "What’s is one thing we don’t know about you?",
    "You're given a sidekick with any superpower of your choosing. What's their name, and what's their power?",
    "Which relationships are you investing the most in right now?",
    "What subject or course do you wish they had offered in school?",
    "Is there anything you think your generation does better than the next generation?",
    "What's the most useless thing you've ever been taught in school?",
    "What's something that will make you smile every time?",
    "What's the best purchase you recently made?",
    "If you could intervene during any historic event, changing history, what would it be? How would things unfold differently?",
    "Do you have any conspiracy theories? If so, what are they?",
    "How have you been lately?",
    "What person in your life do you most admire?",
    "If you were a teacher, what would you teach and what ages would your students be?",
    "If all animals were the same size, what would win in a fight?",
    "What do you consider as red flags in a potential employer or boss?",
    "How would you summarize your last 12 months in one sentence?",
    "What do you think is the most important quality of human civiliation for its continued survival?",
    "What have you been eating lots of lately?",
    "What’s your dream vacation right now? Why?",
    "What's something you've recently let go of, and how has it impacted you?",
    "Who do you go to for advice, and why?",
    "What are you grateful for lately?",
    "How much of your decision to stay in your current job is influenced by comfort and fear versus ambition and fulfillment?",
    "What is the hardest way you’ve learned an important lesson?",
    "What's the worst advice you've ever been given?",
    "What's a fun project you've worked on recently?",
    "If you could ask your future self one thing, what would it be?",
    "What's something expensive you splurge on that you believe is worth the money?",
    "Is there anything you think the previous generation did better than your generation?",
    "What kind of games did you play as a child?",
    "What aspects of how you were raised do you want to continue on to future generations? What aspects do you want to be sure not to repeat?",
    "What's your favorite way to unwind after a busy week?",
    "What does your dream home look like?",
    "Who is someone you think about a lot, that isn't thinking about you nearly as much? What do you make of this?",
    "If you could teach someone just one thing about how to be in a good relationship, what would it be?",
    "What was your parents' relationship like?",
    "What did you learn about yourself from your last relationship?",
    "On a scale of 1-10, how happy are you?",
    "What profession would you be in if you had known about it earlier?",
    "Which of your expectations of someone is causing hurt?",
    "What do you know isn't real, but really wish it existed?",
    "How can you better help others succeed, especially those who often go unnoticed?",
    "What are your biggest goals between now and the next issue of our Letterloop?",
    "What stopped you from following, or encouraged you to follow, your childhood passion?",
    "What is something you're coming to realize?",
    "What's your biggest dream?",
    "What have you been dreaming of eating lately?",
    "What have you previously tolerated that you no longer allow in your life?",
    "What's the most fun you recently had? What did you do, and who were you with?",
    "What's something that will never cease to make you laugh?",
    "You can go back in time and experience any historical event. Where do you go, and when?",
    "What community do you currently feel the most connected to?",
    "What was the most recent thing that made you cry?",
    "What crucial boundary do you need to establish with someone in your life? What's been holding you back?",
    "What's a great name for a pet but a terrible name for a human?",
    "What is an irrational fear you have?",
    "What is a childhood habit or preference that you'll never outgrow?",
    "What's something that tends to ruin your day as of late?",
    "What would you most like to become famous for?",
    "What do you think will still be the same about you 10 years from now?",
    "What do you take for granted?",
    "What movie traumatized you as a kid?",
    "If you could change anything about the way you were raised, what would it be?",
    "What kind of a day have you had so far today?",
    "What's a significant change you're considering or have made?",
    "How has your relationship with your parents changed as you've gotten older?",
    "What's the quirkiest habit you have that you're willing to admit?",
    "What's the most important lesson a friend has taught you?",
    "What one thing (something you made, something you did, something you contributed to) would you like to be remembered by?",
    "If you could telepathically say something that all 8+ billion people on Earth could hear at once, what would it be?",
    "Looking back, what's one decision you made that was a leap of faith? How did it shape where you are today?",
    "What's the most likely cause for the end of humanity, and how do we stop it?",
    "Can you share a personal goal that you haven't achieved yet and why it's important to you?",
    "What did you recently fail at? What did you learn from it?",
    "What traits in others are you attracted to?",
    "If you could start your own charity, what would it focus on?",
    "What trait do you admire in others but don't possess yourself?",
    "What are 3 words you'd used to describe how you currently feel?",
    "What is something that is important to you that you never really talk about?",
    "Did your household ever have a cooking disaster, or a meal that turned out really badly one time?",
    "What's a professional setback or shortfall you recently experienced, and how has it influenced you?",
    "What do you consider as red flags in a potential romantic relationship?",
    "If you could choose one experience from your life that your child could also have, what would it be?",
    "What is the one thing you've made that you're the most proud of?",
    "What's the best outcome of a serendipitous event you've experienced in your life?",
    "What trends do you foresee in your industry in the next five years?",
    "What's one rule you'd put in place if you ruled the world for a day?",
    "If you could try out any other profession for a day, what would it be?",
    "Have you ever had an epiphany? What was it about, and what sparked the realization?",
    "Have you ever had to negotiate salary or a promotion? What's your strategy?",
    "What's something you did recently that took courage?",
    "Who here is most likely to bring an axe to a pillow fight?",
    "If you had to choose a theme song for your life, what would it be?",
    "What's the hardest part about maintaining relationships for you?",
    "What's something you strongly believed in your childhood that you no longer feel sure about?",
    "What do you think all happy people have in common?",
    "Who is someone that you recently issued a genuine apology, and what was it for?",
    "Do you think you fit a particular stereotype? Which one, and why?",
    "What was your relationship like with your siblings growing up? If you didn't have them, who did you spend a lot of time with?",
    "What's something that you wish was easier for you?",
    "Have you ever had a mentor, and what was the most important thing they taught you?",
    "What is your best advice on how to apologize?",
    "What single event or decision do you think most affected the rest of your life? Was there a turning point in your life?",
    "Have you learned the lesson of forgiveness? Why or why not?",
    "What actions, if taken, would make you proud of yourself a month from now, regardless of the outcome?",
    "What's the most bizarre dream you've ever had?",
    "How do you approach networking, and have you had any success stories?",
    "Without saying what the category is, what are your top five?",
    "What are some of your recent highlights and lowlights?",
    "What's one piece of critical feedback you've received? How did you act on it?",
    "Which childhood book or story influenced you the most?",
    "How would you describe your relationship with yourself in a single word?",
    "How well are you taking care of yourself lately?",
    "What's the most enjoyable project you've worked on recently?",
    "How do you reconcile the need for financial stability with the desire to pursue a passion that might be less lucrative?",
    "How do you think you'll be completely different from yourself 10 years from now?",
    'What does "success" mean to you, and how has that definition evolved over time?',
    "What instantly makes you think less of someone?",
    "What do you wish people would talk more about right now?",
    "What did you learn about the concept of love from your parents? Is there anything you want to keep, or anything you want to let go?",
    "What's a new skill or knowledge you're learning right now?",
    "What's something you're frequently complimented on?",
    "What behavior or trait immediately makes you respect someone?",
    "What first impression do you hope you make on people?",
    "What principle do you hold that you would never compromise on, even under pressure?",
    "What's something you're looking forward to doing or experiencing?",
    "Which is more important, nature or nurture?",
    "What is something you've become increasingly interested in the more you've learned about it over time?",
    "What’s a mantra or affirmation you resonate with right now?",
    "Which superhero’s powers do you feel are underestimated?",
    "What's one thing you wish you had known when you started your career?",
    "What's one work-related skill you'd like to develop, and why?",
    "If you had the power to completely eradicate one disease, which would you choose to eliminate?",
    "You can go back in time for 5 minutes. What would you do?",
    "To what degree do you modify your behavior based on who you're with? Do you think this is good or bad?",
    "If you had to skip on meal every day for the rest of your life, which meal would it be?",
    "Would the best version of yourself be in your current job? If not, what keeps you there?",
    "If you had a magic wand, how would your life magically be better a month from now?",
    "If you could travel anywhere in the world right now, where would you go and why?",
    "How do you stay productive and motivated when working from home?",
    "What's a compliment you recently received?",
    "What was the best birthday gift you ever got?",
    "What was the sickest you ever got, as a child?",
    "What behavior or trait immediately makes you trust someone?",
    "Who here is is most likely to join the secret service?",
    "What was the last fear you overcame and how?",
    "If you had 9 lives, what would you do with them?",
    "If you could be the CEO of any company, what company would you choose?",
    "What's something other people commonly do that you avoid, and are proud of doing so?",
    "Who in life has inspired you the most?",
    "What career decisions have you made based on fear? What decisions have been based on confidence?",
    "What's the most unusual food you've ever tried, and would you eat it again?",
    "What is something you've done that you recommend everyone do before they die?",
    "When have you felt the most connected to something greater than yourself, and what were the circumstances?",
    "If you were in a zombie apocalypse and you could only choose 3 people, would you be on your team?",
    "Are there any inner thoughts you have that bother you?",
    "How do you describe your current job to someone who's not in your industry?",
    "What would you like to thank yourself for right now?",
    "What was the scariest moment of your life thus far?",
    "What’s one thing that brings you energy and joy lately?",
    "What's something you've achieved that you never thought possible for yourself?",
    "Where you currently facing uncertainty or unknown, and how are you navigating it?",
    "Who here is is most likely to call in sick at work just to travel for a concert in another state?",
    "You can impart one understanding about human relationships to your child. What insight do you choose to share?",
    "What's a recent disagreement or conflict you had in the workplace? How did you handle it?",
    "How do you think your profession will change in the future, and how are you preparing for it?",
    "What or who do you have an unhealthy relationship with?",
    "What's your secret talent that no one would expect you to have?",
    "What behaviors will you no longer accept in your relationships?",
    "How do you find balance between your personal and professional life?",
    "What was your most memorable moment with your parent(s)?",
    "What tools or apps do you find indispensable for your work?",
    "What's something you'd like to do, but have a hard time acting on?",
    "What is your most terrible memory?",
    "What are the top three qualities of your ideal partner?",
    "What is something you love, that everyone else hates?",
    "What's the best lesson you've learned from a difficult situation?",
    "If you had the power to completely solve one social or political issue affecting the world today, which would you choose?",
    "What is your biggest accomplishment outside of academia and work?",
    "If you were reincarnated as an animal based on your personality, what animal do you think you would come back as?",
    "What is something that's easy for you but seems difficult for most other people?",
    "What past compromises do you refuse to make now?",
    "If you could pick a new first name for yourself, what name would you choose and why?",
    "What's your ideal first date?",
    "If you could have any author write your life story, who would you choose?",
    "If you could have dinner with any person, living or deceased, who would it be and why?",
    "What's something people are surprised to learn about you?",
    "What's a significant professional challenge you overcame in the last year?",
    "Can you share a personal tradition that holds deep meaning for you, and explain its origin?",
    "What were some of my most challenging learning moments in your career, and what made them so?",
    "What song is 10/10 in your book, but no one has heard of it?",
    "What behavior or trait immediately makes you like someone?",
    "You just inherited $10,000,000. How does your life change tomorrow?",
    "Is there something you wish everybody knew about you without you having to tell them?",
    "If you could promote one value or ethic in the world, what would it be and why do you think it's vital?",
    "What's the best advice you've ever received?",
    "If you were a dictator of a small country, what crazy dictator things would you do?",
    "What are you addicted to lately?",
    "What's been on your mind a lot lately?",
    "In what way do you differ most from your romantic partner? In what way are you most similar?",
    "What would people be surprised to learn you spend a lot of time on at work?",
    "Do you have any biases you're aware of?",
    "What was your biggest win lately?",
    'What’s your take on the common career advice to "follow your passion"?',
    "Spiritually, do you believe in something bigger than yourself? What inspired this belief?",
    "What would you consider to be a 'dream job', and how close is your current job to that ideal?",
    "What's your favorite toy?",
    "What's a goal or project you've made progress on?",
    "Thinking about your current #1 goal, what makes you optimistic you'll achieve it?",
    "If you had to get a tail, what tail would you want and what would you use it for?",
    "What is the smallest thing for which you are grateful?",
    "If you could create a new holiday, what would it celebrate?",
    "What life experience has shaped you the most, and in what way?",
    "What's your earliest memory?",
    "Is there anything you think your generation does better than the previous generation?",
    "What is the most trivial thing about which you have a strong opinion?",
    "Does anybody beside yourself know your deepest secret? Do you ever intend to tell anyone?",
    "What boundary did you recently set that has improved your relationship with someone?",
    "If you have siblings, how do you (or did you) quarrel with them?",
    "What's a challenge you recently faced?",
    "What's one thing you recently did for yourself?",
    "What do you believe is the most significant factor in shaping one's destiny, and how much control does one have over it?",
    "When you think of the legacy you want to leave, does your current job contribute to that vision?",
    "What life event did you learn the most from? Would you change it?",
    "What do you feel like you’re really good at?",
    "Are you known for having a personal catchphrase, or something you say often?",
    "What trait signals to you that someone is wise?",
    "What's something you could talk about for hours right now?",
    "What skill of yours are you most proud of?",
    "What is the quality you admire the most in the person you dislike the most?",
    "How can you take better care of yourself? How will you make that happen?",
    "What lesson have you had to learn again and again?",
    "How have you stepped out of your comfort zone recently?",
    "What's that one thing you keep buying or doing even though you know it's unhealthy?",
    "What are your best habits? How did you develop them?",
    "How do you contribute to a positive work environment or culture?",
    "What quality do you most appreciate about your partner?",
    "What's a personal value or belief you've been reflecting on?",
    "What do you consider as red flags in a potential friendship?",
    "Who in your life would you trust with your deepest secret?",
    "Who helped you recently?",
    "What bad habits would you like to get rid of? What steps do you need to take to make that happen?",
    "If you could have a superpower that helps you in your current job, what would it be?",
    "What's the most valuable lesson you've learned from a culture different from your own?",
    "What's the most important lesson you've learned about leadership?",
    "What's something you're interested to learn more about?",
    "Who here is is most likely to establish a scientific law?",
    "What's the most exciting improvement you've been seeing in yourself recently?",
    "If you had the power of perfect memory recall, what’s the first memory you’d revisit?",
    "What is one your core principles in life that is guiding you at this time?",
    "Is there anything you think the next generation will do better than your generation?",
    "What is the most memorable meal you've ever had? (It can be good or bad.) What made it so memorable?",
    "It's \"Freaky Friday\". You wake up in someone else's body for a day. Who would you like to wake up us, and have them inhabit your body instead?",
    "What's one thing about you that hasn't changed in the last 10 years?",
    "What do you think is the most misunderstood aspect of your personality by others?",
    "Which form of self-expression has become increasingly important to you?",
    "What's a difficult conversation you've been meaning to have?",
    "What made you happy today?",
    "Name one thing that stresses you out without fail.",
    "If you could only use five words, how would you describe yourself?",
    "Who here is most likely to call in sick at work just to travel for a concert in another state?",
    "Think of the best teacher you've ever had. What did they teach, and what made them so special?",
    "What's something you're absolutely convinced is going to happen in the future?",
    "If you were a pizza topping, what would you be and why?",
    "What's some surprising feedback you recently received?",
    "What area in your life do you feel you’re making progress? Not making progress?",
    "Are you waiting on someone or something to progress in an aspect of your life?",
    "Who here is most likely to dedicate their life trying to go to another planet?",
    "If you could witness any event from the past, present, or future, what would it be and why?",
    "Where do you feel you're improving the most?",
    "What professional accomplishment are you most proud of and why?",
    "How would you describe your approach to your career so far?",
    "What is your favorite word and why?",
    "If seasons never changed, which would you most like to live in eternally?",
    "Which best describes you? An introvert or an extrovert?",
    "What's a current trend you find concerning?",
    "A surprise package arrives at your doorstep — it's from everyone here! What's inside?",
    "What is your best season of the year? Why?",
    "What's something very strange that happened to you?",
    "If you could choose one superpower, but it had to be extremely specific and unusual, what would it be?",
    "What’s something that made you laugh recently?",
    "Have you picked up any new skills at your job this year?",
    "What's a deep or difficult question you've been pondering lately?",
    "What skills or passions are you not currently utilizing in your job?",
    "What's one thing you've never done but feels like it's something you need to do in your lifetime?",
    "What quality are you currently cultivating in yourself?",
    "Where do you see yourself professionally a year from now?",
    "What's a recent moment in which you're proud that you spoke up?",
    "Who here is is most likely to have the most children?",
    "What's something you are really into right now?",
    "What elements of your daily routine have become non-negotiable lately?",
    "In three words, how would your family and friends describe you?",
    "Is there anyone in your life being impacted by your insecurities?",
    "What's the one thing you would like to change about yourself?",
    "What aspects of life are you loving most right now?",
    "What was your least favorite food growing up?",
    "What's an unconventional piece of advice that has had a significant impact on your life?",
    "What's a memorable lesson you've learned from a mistake you've made?",
    "What's a funny or interesting story from your week?",
    "You have to start a business. If you already have one, it can't be your current one. What would you name it, and what would it do?",
    "You just became a new member of the Spice Girls. What's Spice name do you create for yourself?",
    "What is one action that would make today a success?",
    "Who here is most likely to leave their inheritance to a ferret that only has a 3-year lifespan?",
    "If you were perpetually surrounded by one aroma (asides your own, natural scent) which you and everyone around you could smell, what would it be?",
    "What's a belief you held strongly that you changed your mind about?",
    "What's a recent decision that was hard to make?",
    "Does your current job challenge you to grow in the ways you truly want? If not, what’s missing?",
    "What is something you hate, that everyone else loves?",
    "What's your favorite memory with your family?",
    "What is your most regretful purchase?",
    "If you could have any mythical creature as a pet, which one would you choose?",
    "Do you feel you're operating in a sustainable way?",
    "Who here is is most likely to look almost the same years from now?",
    "You're gifted 24 hours where you and your pet(s) are suddenly able to talk to each other. What would you want to tell them, and how would you want to spend your time with them?",
    "What would you do if there were no internet for the next 24 hours?",
    "If you could know for certain the answer to any question, what would that question be?",
    "How do you show someone you care about them?",
    "What's your most common feeling lately?",
    "Explain your current feelings in life to a 3 year old.",
    "What indulgence do you currently spend the most money on?",
    "What is one thing you didn’t do so well recently?",
    "What's the best compliment you've ever received?",
    "What do you plan to learn in the coming days?",
    "What do you wish people would ask you more about right now?",
    "What advice would you give about maintaining long-lasting relationships?",
    "If your life was a story, what chapter would you currently be in, and what would its title be?",
]
