services:
  api:
    image: prod-ring-api
    command: "uvicorn ring.fast:app --proxy-headers --host 0.0.0.0 --port ${API_PORT} --reload"
    mem_limit: 300m
    expose:
      - "${API_PORT}"
    env_file:
      - ./.env
    platform: linux/amd64

  nginx:
    mem_limit: 300m
    volumes:
      - ./prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    platform: linux/amd64

  worker:
    image: prod-ring-worker
    env_file:
      - ./.env
    mem_limit: 150m
    platform: linux/amd64
  beat:
    mem_limit: 150m
    image: prod-ring-beat
    env_file:
      - ./.env
    platform: linux/amd64
  flower:
    mem_limit: 100m
    image: prod-ring-flower
    env_file:
      - ./.env
    ports:
      - "8003:5555"
    platform: linux/amd64

  frontend:
    mem_limit: 300m
    container_name: ring-frontend
    image: prod-ring-frontend
    build:
      context: ./react
      dockerfile: client.Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    platform: linux/amd64
      

volumes:
  pgdata:
