services:
  api:
    container_name: ring-api
    build: 
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      # image: email_circle-api
    command: "uvicorn ring.fast:app --proxy-headers"
    volumes:
      - ./ring:/src/ring
    environment:
      - PYTHONPATH=.
    networks:
      - default

  nginx:
    restart: unless-stopped
    container_name: ring-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - default

  worker:
    container_name: ring-worker
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      # image: email_circle-worker
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app worker --loglevel=debug"
    depends_on:
      - redis
    networks:
      - default
  beat:
    container_name: ring-beat
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      # image: email_circle-beat
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app beat"
    depends_on:
      - redis 
      - worker
    networks:
      - default
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - default
  flower:
    container_name: ring-flower
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app flower"
    depends_on:
      - redis
      - worker
    profiles: ["debug"]
    networks:
      - default

networks:
  default:
    name: ring-network
    external: true