services:
  api:
    command: "uvicorn ring.fast:app --proxy-headers --host 0.0.0.0 --port ${API_PORT} --reload"
    expose:
      - "${API_PORT}"
    env_file:
      - ./.env

  nginx:
    volumes:
      - ./prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro

  worker:
    env_file:
      - ./.env
  beat:
    env_file:
      - ./.env
  flower:
    env_file:
      - ./.env
    ports:
      - "8003:5555"

  next:
    container_name: next
    build:
      context: ./client
      dockerfile: client.Dockerfile
      

volumes:
  pgdata:
