services:
  api:
    restart: unless-stopped
    container_name: ring-api
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      # image: email_circle-api
    command: "uvicorn ring.fastapp.fast:app --proxy-headers"
    volumes:
      - ./ring:/src/ring
    environment:
      - PYTHONPATH=.
    networks:
      - default

  nginx:
    restart: unless-stopped
    container_name: ring-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - default

networks:
  default:
    name: ring-network
    external: true
