services:
  test-cockroach:
    image: cockroachdb/cockroach:v25.2.1
    container_name: ring-test-cockroach
    restart: unless-stopped
    profiles: [ "test" ]
    command: start-single-node
    ports:
      - 8008:8080
    environment:
      - COCKROACH_USER=ringcockroach
      - COCKROACH_PASSWORD=ringcockroach
      - COCKROACH_DATABASE=test
    networks:
      - default
  test-runner:
    image: ring-test-runner
    container_name: ring-test-runner
    command: [ "pytest", "-c", "ring/tests/pytest.ini" ]
    build:
      context: ./ring
      dockerfile: test.Dockerfile
      target: ring
    depends_on:
      - test-cockroach
    volumes:
      - ./ring:/src/ring
    profiles: [ "test" ]
    environment:
      - PYTHONPATH=.
      - JWT_SIGNING_KEY=secret
      - JWT_SIGNING_ALGORITHM=HS256
      - sqlalchemy_database_uri=blank
      - cockroach_database_uri=cockroachdb://ringcockroach:ringcockroach@test-cockroach:26257/test
      - environment=test
      - VAPID_PRIVATE_KEY=private_key
      - LLM_SERVICE_API_KEY=test
    networks:
      - default

networks:
  default:
    name: ring-network
    external: true
