services:
  api:
    command: "uvicorn ring.fast:app --proxy-headers --host 0.0.0.0 --port ${API_PORT} --reload"
    expose:
      - "${API_PORT}"
    env_file:
      - ./.env

  nginx:
    volumes:
      - ./prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro

  worker:
    env_file:
      - ./.env
    mem_limit: 300m
  beat:
    env_file:
      - ./.env
  flower:
    env_file:
      - ./.env
    ports:
      - "8003:5555"

  frontend:
    container_name: ring-frontend
    build:
      context: ./react
      dockerfile: client.Dockerfile
      args:
        - VITE_API_URL=http://ec2-54-221-74-168.compute-1.amazonaws.com
      

volumes:
  pgdata:
