services:
  api:
    command: "uvicorn ring.fast:app --host 0.0.0.0 --port ${API_PORT} --reload"
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env

  worker:
    env_file:
      - ./.env
  beat:
    env_file:
      - ./.env
  flower:
    env_file:
      - ./.env
    ports:
      - "8003:5555"
      

volumes:
  pgdata:
