services:
  api:
    container_name: ring-api
    build: 
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      image: email_circle-api
    command: "uvicorn ring.fast:app --proxy-headers"
    volumes:
      - ./ring:/src/ring
    environment:
      - PYTHONPATH=.

  nginx:
    restart: unless-stopped
    container_name: ring-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - api

  worker:
    container_name: ring-worker
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      image: email_circle-worker
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app worker"
    depends_on:
      - redis
  beat:
    container_name: ring-beat
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
      image: email_circle-beat
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app beat"
    depends_on:
      - redis 
      - worker
  redis:
    image: redis:alpine
    expose:
      - 6379
  flower:
    container_name: ring-flower
    build:
      context: ./ring
      dockerfile: ring.Dockerfile
      target: ring
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker.celery_app flower"
    depends_on:
      - redis
      - worker
    profiles: ["debug"]