services:
  api:
    container_name: ring-api
    build: 
      context: ./ring
      dockerfile: ring.Dockerfile
    command: "uvicorn ring.fast:app --log-level debug --host 0.0.0.0 --port ${API_PORT} --reload"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./ring:/src/ring
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=.
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: client.Dockerfile
  worker:
    build:
      context: ./ring
      dockerfile: celery.Dockerfile
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker worker --loglevel=debug"
    env_file:
      - ./.env
    environment:
      - DB_PORT=8000
    depends_on:
      - redis
  beat:
    build:
      context: ./ring
      dockerfile: celery.Dockerfile
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker beat --loglevel=debug"
    env_file:
      - ./.env
    depends_on:
      - redis 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  flower:
    build:
      context: ./ring
      dockerfile: celery.Dockerfile
    volumes:
      - ./ring:/src/ring
    command: "celery --app=ring.worker flower"
    # image: mher/flower
    env_file:
      - ./.env
    ports:
      - "8003:5555"
    depends_on:
      - redis
      - worker
  db:
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -port ${DB_PORT}"
    image: "amazon/dynamodb-local:latest"
    container_name: ring-db 
    ports:
      - ${DB_PORT}:8000
    volumes:
      - dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

volumes:
  dynamodb: