services:
  api:
    container_name: ring-api
    build: ./ring
    command: "uvicorn fast:app --log-level debug --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    volumes:
      - ./ring:/src
    env_file:
      - ./.env
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'us-east-1'
    depends_on:
      - db
    links:
      - db
  redis:
    image: redis:alpine
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: ring-db 
    ports:
      - "8000:8000"
    volumes:
      - dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

volumes:
  dynamodb: