[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["ring", "dev_util"]
namespaces = false

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select  = [
    "I001",
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"ring/alembic/versions/**.py" = ["F401"]

[tool.uv.sources]
llm-service = { path = "ring/packages/service_clients/llm_service" }
llm = { workspace = true }

[tool.uv.workspace]
members = [
    "llm"
]

[tool.pyright]
typeCheckingMode = "basic"


[project]
name = "ring"
version = "0.1.0"
description = "A clone of LetterLoop"
requires-python = ">=3.12"
dependencies = [
    "pynamodb ~= 5.0",
    "pydantic ~= 2.5",
    "fastapi[all] ~= 0.104",
    "shortuuid ~= 1.0",
    "Redis ~= 5.0",
    "boto3 ~= 1.34",
    "boto3-stubs[essential,ses] ~= 1.34",
    "SQLAlchemy ~= 2.0",
    "sqlalchemy[asyncio] ~= 2.0",
    "pgcli ~= 4.0",
    "ipython ~= 8.20",
    "alembic ~= 1.13",
    "python-jose[cryptography] ~= 3.3",
    "pwdlib[argon2,bcrypt] ~= 0.2",
    "watchdog ~= 4.0",
    "mypy_boto3_ses ~= 1.34",
    "click ~= 8.1.7",
    "pyjwt ~= 2.8",
    "ipython-autoimport",
    "ipython-autotime",
    "pprintpp",
    "ruff",
    "bs4",
    "requests",
    "pre-commit>=4.0.1",
    "psycopg2-binary>=2.9.10",
    "pywebpush>=2.0.3",
    "loguru>=0.7.3",
    "sqlalchemy-json>=0.7.0",
    "sqlalchemy-cockroachdb>=2.0.2",
    "apscheduler>=3.11.0",
    "pgvector>=0.4.1",
    "pycasbin>=1.45.0",
    "casbin-sqlalchemy-adapter>=1.4.0",
    "casbin>=1.43.0",
    "websockets>=14.1",
    "httpx-ws>=0.7.2",
]

[dependency-groups]
dev = [
    "pytest-factoryboy>=2.7.0",
    "pytest>=8.3.4",
    "psycopg-binary",
    "pytest-pretty>=1.2.0",
    "pytest-xdist>=3.6.1",
    "ipdb>=0.13.13",
]
ai = [
    "llm-service",
]

[project.scripts]
ring = "dev_util.dev:dev"
