packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - "src/**"
  - "apps/**"
  - 'packages/**'
  # if required, exclude some directories
  - '!**/test/**'

allowBuilds:
  "@tailwindcss/oxide": true
  "@tailwindcss/oxide-linux-x64-gnu": true

