FROM python:3.12.1-bullseye AS llm

WORKDIR /src

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install uv
COPY ./llm_requirements.txt ./
RUN uv pip install -r llm_requirements.txt --system --no-cache

ARG RING_GIT_SHA
ARG RING_GIT_SHORT_SHA
ARG RING_GIT_BRANCH
ARG RING_GIT_SUBJECT
ARG RING_GIT_AUTHOR_NAME
ARG RING_GIT_AUTHOR_EMAIL
ARG RING_GIT_COMMITTED_AT
ARG RING_GIT_DIRTY
ENV RING_BUILD_GIT_SHA=${RING_GIT_SHA}
ENV RING_BUILD_GIT_SHORT_SHA=${RING_GIT_SHORT_SHA}
ENV RING_BUILD_GIT_BRANCH=${RING_GIT_BRANCH}
ENV RING_BUILD_GIT_SUBJECT=${RING_GIT_SUBJECT}
ENV RING_BUILD_GIT_AUTHOR_NAME=${RING_GIT_AUTHOR_NAME}
ENV RING_BUILD_GIT_AUTHOR_EMAIL=${RING_GIT_AUTHOR_EMAIL}
ENV RING_BUILD_GIT_COMMITTED_AT=${RING_GIT_COMMITTED_AT}
ENV RING_BUILD_GIT_DIRTY=${RING_GIT_DIRTY}
LABEL org.opencontainers.image.source="https://github.com/neil-sriv/ring"
LABEL org.opencontainers.image.revision="${RING_GIT_SHA}"
LABEL org.opencontainers.image.title="ring-llm"