"""generic embedding column

Revision ID: 0852b676e883
Revises: c8ebbe0240e5
Create Date: 2025-05-19 00:02:29.945644

"""

from __future__ import annotations

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0852b676e883"
down_revision: Union[str, None] = "c8ebbe0240e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hybrid_search_document",
        sa.Column(
            "text_embedding_768",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            nullable=False,
        ),
    )
    op.execute(
        """
        CREATE VECTOR INDEX IF NOT EXISTS embedding_768_vector_idx ON hybrid_search_document (text_embedding_768);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS embedding_768_vector_idx;
        """
    )
    op.drop_column(
        "hybrid_search_document",
        "text_embedding_768",
        if_exists=True,
    )
    # ### end Alembic commands ###
