"""add letter.letter_type column

Revision ID: 12f44d4b5f80
Revises: e66b58976126
Create Date: 2025-07-12 23:29:55.856204

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12f44d4b5f80"
down_revision: Union[str, None] = "e66b58976126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "letter",
        sa.Column(
            "letter_type",
            sa.String(),
            nullable=False,
            server_default="CYCLIC",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("letter", "letter_type")
    # ### end Alembic commands ###
