"""add hybrid search association document index

Revision ID: 200bce5abdcc
Revises: 45bf29f5dbb8
Create Date: 2026-08-10 05:34:53.571033

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "200bce5abdcc"
down_revision: Union[str, None] = "45bf29f5dbb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f(
            "ix_hybrid_search_document_association_hybrid_search_document_id"
        ),
        "hybrid_search_document_association",
        ["hybrid_search_document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(
            "ix_hybrid_search_document_association_hybrid_search_document_id"
        ),
        table_name="hybrid_search_document_association",
    )
    # ### end Alembic commands ###
