"""group cycle length

Revision ID: 2c480092c350
Revises: f3ff76cffae4
Create Date: 2025-02-27 01:56:00.292899

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c480092c350"
down_revision: Union[str, None] = "f3ff76cffae4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column(
            "cycle_length", sa.Integer(), nullable=False, server_default="30"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "cycle_length")
    # ### end Alembic commands ###
