"""add notification table

Revision ID: 2d8ef97d8330
Revises: cd37cfa88894
Create Date: 2026-08-24 14:08:10.136814

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d8ef97d8330"
down_revision: Union[str, None] = "cd37cfa88894"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("target_api_id", sa.String(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["user.id"],
            name="notification_recipient_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_api_identifier"),
        "notification",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notification_created_at"),
        "notification",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_id"), "notification", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_recipient_id"),
        "notification",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_target_api_id"),
        "notification",
        ["target_api_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_type"), "notification", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_type"), table_name="notification")
    op.drop_index(
        op.f("ix_notification_target_api_id"), table_name="notification"
    )
    op.drop_index(
        op.f("ix_notification_recipient_id"), table_name="notification"
    )
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_index(
        op.f("ix_notification_created_at"), table_name="notification"
    )
    op.drop_index(
        op.f("ix_notification_api_identifier"), table_name="notification"
    )
    op.drop_table("notification")
    # ### end Alembic commands ###
