"""create invite model

Revision ID: 3b9996219fea
Revises: b3cf607cc8e6
Create Date: 2024-09-06 05:35:45.153952

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b9996219fea"
down_revision: Union[str, None] = "b3cf607cc8e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("ttl", sa.Float(), nullable=False),
        sa.Column("inviter_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invite_api_identifier"),
        "invite",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_invite_created_at"), "invite", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_invite_email"), "invite", ["email"], unique=True)
    op.create_index(op.f("ix_invite_id"), "invite", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invite_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_email"), table_name="invite")
    op.drop_index(op.f("ix_invite_created_at"), table_name="invite")
    op.drop_index(op.f("ix_invite_api_identifier"), table_name="invite")
    op.drop_table("invite")
    # ### end Alembic commands ###
