"""add token type column

Revision ID: 462f823cd7d6
Revises: 07ff6f6066f4
Create Date: 2024-10-22 03:16:06.939023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "462f823cd7d6"
down_revision: Union[str, None] = "4a8933606b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "one_time_token", sa.Column("type", sa.String(), nullable=True)
    )
    op.execute("UPDATE one_time_token SET type = 'invite'")

    op.alter_column(
        "one_time_token", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("one_time_token", "type")
    # ### end Alembic commands ###
