"""add short_link table

Revision ID: 5185edcb8391
Revises: 200bce5abdcc
Create Date: 2026-08-13 22:11:41.305163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5185edcb8391"
down_revision: Union[str, None] = "200bce5abdcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "short_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("target_api_id", sa.String(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name="short_link_creator_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_short_link_api_identifier"),
        "short_link",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_short_link_created_at"),
        "short_link",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_short_link_creator_id"),
        "short_link",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_short_link_id"), "short_link", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_short_link_target_api_id"),
        "short_link",
        ["target_api_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_short_link_token"), "short_link", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_short_link_token"), table_name="short_link")
    op.drop_index(op.f("ix_short_link_target_api_id"), table_name="short_link")
    op.drop_index(op.f("ix_short_link_id"), table_name="short_link")
    op.drop_index(op.f("ix_short_link_creator_id"), table_name="short_link")
    op.drop_index(op.f("ix_short_link_created_at"), table_name="short_link")
    op.drop_index(
        op.f("ix_short_link_api_identifier"), table_name="short_link"
    )
    op.drop_table("short_link")
    # ### end Alembic commands ###
