"""add document models for notebook

Revision ID: 67f45611e57a
Revises: b3b636b1af58
Create Date: 2025-08-05 04:57:53.137462

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67f45611e57a"
down_revision: Union[str, None] = "b3b636b1af58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("content", sa.BLOB(), nullable=False),
        sa.Column("latest_snapshot_version", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_documents_api_identifier"),
        "documents",
        ["api_identifier"],
        unique=True,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_documents_created_at"),
        "documents",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )

    op.execute("CREATE SEQUENCE document_edit_version_seq")

    op.create_table(
        "document_edits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delta", sa.BLOB(), nullable=False),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.execute(
        "ALTER TABLE document_edits ALTER COLUMN version SET DEFAULT nextval('document_edit_version_seq')"
    )
    op.create_unique_constraint(
        "unique_document_edit_version",
        "document_edits",
        ["document_id", "version"],
    )
    op.create_index(
        op.f("ix_document_edits_created_at"),
        "document_edits",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_document_edits_created_at"), table_name="document_edits"
    )
    op.execute(
        "DROP INDEX IF EXISTS document_edits@ix_document_edits_created_at CASCADE"
    )
    op.drop_table("document_edits", if_exists=True)
    op.drop_index(
        op.f("ix_documents_created_at"), table_name="documents", if_exists=True
    )

    op.drop_index(
        op.f("ix_documents_api_identifier"),
        table_name="documents",
        if_exists=True,
    )
    op.drop_table("documents", if_exists=True)
    op.execute("DROP SEQUENCE document_edit_version_seq")
    # ### end Alembic commands ###
