"""ott.email column

Revision ID: 6dd27b0c4e82
Revises: 661766eb48e0
Create Date: 2024-11-11 03:17:34.729708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dd27b0c4e82"
down_revision: Union[str, None] = "661766eb48e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "one_time_token", sa.Column("email", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_one_time_token_email"),
        "one_time_token",
        ["email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_one_time_token_email"), table_name="one_time_token")
    op.drop_column("one_time_token", "email")
    # ### end Alembic commands ###
