"""Alembic init; all models

Revision ID: 72e10b4b03de
Revises:
Create Date: 2024-02-18 18:07:15.450964

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72e10b4b03de"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_api_identifier"), "user", ["api_identifier"], unique=True
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_group_api_identifier"),
        "group",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=True)
    op.create_table(
        "letter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "group_id", "number", name="unique_group_letter_number"
        ),
    )
    op.create_index(
        op.f("ix_letter_api_identifier"),
        "letter",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(op.f("ix_letter_id"), "letter", ["id"], unique=False)
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", name="unique_group_schedule"),
    )
    op.create_index(op.f("ix_schedule_id"), "schedule", ["id"], unique=False)
    op.create_table(
        "user_group_assocation",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "letter_to_user_assocation",
        sa.Column("letter_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["letter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("letter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["letter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_api_identifier"),
        "question",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(op.f("ix_question_id"), "question", ["id"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("execute_at", sa.DateTime(), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_execute_at"), "task", ["execute_at"], unique=False
    )
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_schedule_id"), "task", ["schedule_id"], unique=False
    )
    op.create_index(op.f("ix_task_status"), "task", ["status"], unique=False)
    op.create_index(op.f("ix_task_type"), "task", ["type"], unique=False)
    op.create_table(
        "question_to_user_association",
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_response_api_identifier"),
        "response",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(op.f("ix_response_id"), "response", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.has_table(op.get_bind(), "response"):
        op.drop_index(op.f("ix_response_id"), table_name="response")
        op.drop_index(
            op.f("ix_response_api_identifier"), table_name="response"
        )
        op.drop_table("response", if_exists=True)
    if op.get_bind().dialect.has_table(
        op.get_bind(), "question_to_user_association"
    ):
        op.drop_table("question_to_user_association", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "task"):
        op.drop_index(op.f("ix_task_type"), table_name="task", if_exists=True)
        op.drop_index(
            op.f("ix_task_status"), table_name="task", if_exists=True
        )
        op.drop_index(
            op.f("ix_task_schedule_id"), table_name="task", if_exists=True
        )
        op.drop_index(op.f("ix_task_id"), table_name="task", if_exists=True)
        op.drop_index(
            op.f("ix_task_execute_at"), table_name="task", if_exists=True
        )
        op.drop_table("task", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "question"):
        op.drop_index(
            op.f("ix_question_id"), table_name="question", if_exists=True
        )
    if op.get_bind().dialect.has_table(op.get_bind(), "question"):
        op.drop_index(
            op.f("ix_question_api_identifier"),
            table_name="question",
            if_exists=True,
        )
        op.drop_table("question", if_exists=True)
    if op.get_bind().dialect.has_table(
        op.get_bind(), "letter_to_user_assocation"
    ):
        op.drop_table("letter_to_user_assocation", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "user_group_assocation"):
        op.drop_table("user_group_assocation", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "schedule"):
        op.drop_index(
            op.f("ix_schedule_id"), table_name="schedule", if_exists=True
        )
        op.drop_table("schedule", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "letter"):
        op.drop_index(
            op.f("ix_letter_id"), table_name="letter", if_exists=True
        )
        op.drop_index(
            op.f("ix_letter_api_identifier"),
            table_name="letter",
            if_exists=True,
        )
        op.drop_table("letter", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "group"):
        op.drop_index(
            op.f("ix_group_name"), table_name="group", if_exists=True
        )
        op.drop_index(op.f("ix_group_id"), table_name="group", if_exists=True)
        op.drop_index(
            op.f("ix_group_api_identifier"), table_name="group", if_exists=True
        )
        op.drop_table("group", if_exists=True)
    if op.get_bind().dialect.has_table(op.get_bind(), "user"):
        op.drop_index(op.f("ix_user_id"), table_name="user", if_exists=True)
        op.drop_index(op.f("ix_user_email"), table_name="user", if_exists=True)
        op.drop_index(
            op.f("ix_user_api_identifier"), table_name="user", if_exists=True
        )
    op.drop_table("user", if_exists=True)
    # ### end Alembic commands ###
