"""hybrid_search_document

Revision ID: 753be4992cf3
Revises: e52f77a2470a
Create Date: 2025-05-16 06:46:49.694100

"""

from __future__ import annotations

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "753be4992cf3"
down_revision: Union[str, None] = "e52f77a2470a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hybrid_search_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.String(), nullable=False),
        sa.Column("text_tsv", postgresql.TSVECTOR(), nullable=False),
        sa.Column(
            "text_embedding_384",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_hybrid_search_document_created_at"),
        "hybrid_search_document",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.execute(
        """
        CREATE INVERTED INDEX IF NOT EXISTS content_search_inverted_idx ON hybrid_search_document (text_tsv);
        """
    )
    op.execute(
        """
        CREATE VECTOR INDEX IF NOT EXISTS embedding_vector_idx ON hybrid_search_document (text_embedding_384);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hybrid_search_document_created_at"),
        table_name="hybrid_search_document",
        if_exists=True,
    )
    op.execute(
        """
        DROP INDEX IF EXISTS content_search_inverted_idx;
        """
    )
    op.execute(
        """
        DROP INDEX IF EXISTS embedding_vector_idx;
        """
    )
    op.drop_table("hybrid_search_document", if_exists=True)
    # ### end Alembic commands ###
