"""add default question table

Revision ID: 76581aa06774
Revises: 8042a30020a6
Create Date: 2024-10-20 06:54:21.737885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from ring.letters.constants import DEFAULT_QUESTIONS
from ring.letters.models.default_question_model import DefaultQuestion
from ring.parties.models.group_model import Group


# revision identifiers, used by Alembic.
revision: str = "76581aa06774"
down_revision: Union[str, None] = "8042a30020a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_default_question_api_identifier"),
        "default_question",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_default_question_created_at"),
        "default_question",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_default_question_id"),
        "default_question",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###

    session = Session(bind=op.get_bind())
    groups = session.scalars(sa.select(Group)).all()
    for group in groups:
        for q in DEFAULT_QUESTIONS:
            default_question = DefaultQuestion.create(q, group)
            session.add(default_question)
    session.commit()


def downgrade() -> None:
    session = Session(bind=op.get_bind())
    session.execute(sa.delete(DefaultQuestion))
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_default_question_id"), table_name="default_question"
    )
    op.drop_index(
        op.f("ix_default_question_created_at"), table_name="default_question"
    )
    op.drop_index(
        op.f("ix_default_question_api_identifier"),
        table_name="default_question",
    )
    op.drop_table("default_question")
    # ### end Alembic commands ###
