"""add default question table

Revision ID: 76581aa06774
Revises: 8042a30020a6
Create Date: 2024-10-20 06:54:21.737885

"""
from __future__ import annotations

from typing import Sequence, Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

from ring.letters.constants import DEFAULT_QUESTIONS

# revision identifiers, used by Alembic.
revision: str = "76581aa06774"
down_revision: Union[str, None] = "6dd27b0c4e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_default_question_api_identifier"),
        "default_question",
        ["api_identifier"],
        unique=True,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_default_question_created_at"),
        "default_question",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_default_question_id"),
        "default_question",
        ["id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###

    # Get all group IDs
    connection = op.get_bind()
    groups = connection.execute(text('SELECT id FROM "group"')).fetchall()

    # Insert default questions for each group
    for group in groups:
        group_id = group[0]
        for question in DEFAULT_QUESTIONS:
            # Generate a unique API identifier using UUID4
            api_id = f"dfqstn_{uuid4()}"
            connection.execute(
                text(
                    """
                    INSERT INTO default_question (api_identifier, question_text, group_id)
                    VALUES (:api_id, :question, :group_id)
                    """
                ),
                {"api_id": api_id, "question": question, "group_id": group_id},
            )


def downgrade() -> None:
    # Delete all default questions
    connection = op.get_bind()
    connection.execute(text("DELETE FROM default_question"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_default_question_id"), table_name="default_question"
    )
    op.drop_index(
        op.f("ix_default_question_created_at"), table_name="default_question"
    )
    op.drop_index(
        op.f("ix_default_question_api_identifier"),
        table_name="default_question",
    )
    op.drop_table("default_question")
    # ### end Alembic commands ###
