"""add group ref to invite model

Revision ID: 7a4446c9936b
Revises: 3b9996219fea
Create Date: 2024-09-07 02:03:42.980259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4446c9936b'
down_revision: Union[str, None] = '3b9996219fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invite', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.drop_column('invite', 'group_id')
    # ### end Alembic commands ###
