"""make invite.ott non-null

Revision ID: 84618d011254
Revises: 07ff6f6066f4
Create Date: 2024-10-27 02:24:25.575582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import IntegrityError


# revision identifiers, used by Alembic.
revision: str = "84618d011254"
down_revision: Union[str, None] = "07ff6f6066f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column(
            "invite",
            "one_time_token_id",
            existing_type=sa.INTEGER(),
            nullable=False,
        )
    except IntegrityError as e:
        raise Exception(
            f"Encountered error {type(e)}: {e}\n***\nPlease run: ring run script --script ring/scripts/backfill_invite_ott.py"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invite",
        "one_time_token_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
