"""add share_link table

Revision ID: 9537ee51f144
Revises: 200bce5abdcc
Create Date: 2026-08-13 23:49:33.355957

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9537ee51f144"
down_revision: Union[str, None] = "200bce5abdcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "share_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("target_api_id", sa.String(), nullable=False),
        sa.Column("created_by_api_id", sa.String(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_share_link_api_identifier"),
        "share_link",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_share_link_created_at"),
        "share_link",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_link_id"), "share_link", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_share_link_target_api_id"),
        "share_link",
        ["target_api_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_share_link_token"), "share_link", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_share_link_token"), table_name="share_link")
    op.drop_index(op.f("ix_share_link_target_api_id"), table_name="share_link")
    op.drop_index(op.f("ix_share_link_id"), table_name="share_link")
    op.drop_index(op.f("ix_share_link_created_at"), table_name="share_link")
    op.drop_index(
        op.f("ix_share_link_api_identifier"), table_name="share_link"
    )
    op.drop_table("share_link")
    # ### end Alembic commands ###
