"""document group FK

Revision ID: 9f2f7995f154
Revises: 67f45611e57a
Create Date: 2025-09-23 04:19:09.548967

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f2f7995f154"
down_revision: Union[str, None] = "67f45611e57a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("group_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "documents", "group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "group_id")
    # ### end Alembic commands ###
