"""add spotify account linking

Revision ID: 9fb2468cc3b2
Revises: dba1e8d3b15a
Create Date: 2026-10-07 05:40:59.279283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fb2468cc3b2"
down_revision: Union[str, None] = "dba1e8d3b15a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_spotify_playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("spotify_playlist_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "group_id", name="uq_user_group_spotify_playlist"
        ),
    )
    op.create_index(
        op.f("ix_user_spotify_playlist_created_at"),
        "user_spotify_playlist",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_spotify_playlist_group_id"),
        "user_spotify_playlist",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_spotify_playlist_id"),
        "user_spotify_playlist",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_spotify_playlist_user_id"),
        "user_spotify_playlist",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "user", sa.Column("spotify_refresh_token", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "spotify_refresh_token")
    op.drop_index(
        op.f("ix_user_spotify_playlist_user_id"),
        table_name="user_spotify_playlist",
    )
    op.drop_index(
        op.f("ix_user_spotify_playlist_id"), table_name="user_spotify_playlist"
    )
    op.drop_index(
        op.f("ix_user_spotify_playlist_group_id"),
        table_name="user_spotify_playlist",
    )
    op.drop_index(
        op.f("ix_user_spotify_playlist_created_at"),
        table_name="user_spotify_playlist",
    )
    op.drop_table("user_spotify_playlist")
    # ### end Alembic commands ###
