"""add new column send_at to letter

Revision ID: ab536d574009
Revises: c464c74a2365
Create Date: 2024-07-02 23:47:20.332886

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab536d574009"
down_revision: Union[str, None] = "c464c74a2365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("letter", sa.Column("send_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("letter", "send_at")
    # ### end Alembic commands ###
