"""one time use invite token

Revision ID: b2561e7b05f3
Revises: 8042a30020a6
Create Date: 2024-10-11 21:36:28.798732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2561e7b05f3"
down_revision: Union[str, None] = "8042a30020a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invite",
        sa.Column(
            "used",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.alter_column(
        "invite",
        "used",
        existing_type=sa.INTEGER(),
        server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite", "used")
    # ### end Alembic commands ###
