"""add search indexing to db

Revision ID: b3b636b1af58
Revises: af3ebab1c074
Create Date: 2025-08-04 02:48:15.003856

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3b636b1af58"
down_revision: Union[str, None] = "af3ebab1c074"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE VECTOR INDEX IF NOT EXISTS embedding_vector_idx ON hybrid_search_document (text_embedding_768);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS embedding_vector_idx;
        """
    )
    # ### end Alembic commands ###
