"""one time use token model

Revision ID: c3f66ba34f6f
Revises: b2561e7b05f3
Create Date: 2024-10-13 22:41:45.888119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3f66ba34f6f"
down_revision: Union[str, None] = "b2561e7b05f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "one_time_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("ttl", sa.Float(), nullable=False),
        sa.Column(
            "used",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_one_time_token_created_at"),
        "one_time_token",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_one_time_token_id"), "one_time_token", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_one_time_token_id"), table_name="one_time_token")
    op.drop_index(
        op.f("ix_one_time_token_created_at"), table_name="one_time_token"
    )
    op.drop_table("one_time_token")
    # ### end Alembic commands ###
