"""replace text_tsv with computed column

Revision ID: c8ebbe0240e5
Revises: 753be4992cf3
Create Date: 2025-05-16 07:26:10.241413

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision: str = "c8ebbe0240e5"
down_revision: Union[str, None] = "753be4992cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS content_search_inverted_idx;
        """
    )
    op.drop_column("hybrid_search_document", "text_tsv", if_exists=True)
    op.execute(
        """
        ALTER TABLE hybrid_search_document ADD COLUMN IF NOT EXISTS text_tsv TSVECTOR AS (to_tsvector('english', raw_text)) STORED;
        """
    )
    op.execute(
        """
        CREATE INVERTED INDEX IF NOT EXISTS content_search_inverted_idx ON hybrid_search_document (text_tsv);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP INDEX IF EXISTS content_search_inverted_idx;
        """
    )
    op.drop_column("hybrid_search_document", "text_tsv", if_exists=True)
    op.add_column(
        "hybrid_search_document",
        sa.Column(
            "text_tsv",
            postgresql.TSVECTOR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute(
        """
        CREATE INVERTED INDEX IF NOT EXISTS content_search_inverted_idx ON hybrid_search_document (text_tsv);
        """
    )
    # ### end Alembic commands ###
