"""add s3 file column to response

Revision ID: d10224a3e726
Revises: 72e10b4b03de
Create Date: 2024-06-05 07:11:07.320641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10224a3e726'
down_revision: Union[str, None] = '72e10b4b03de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('_image_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', '_image_file')
    # ### end Alembic commands ###
