"""remove email uniqueness for invite and fix cascade relationships

Revision ID: d4e29ddb3e5d
Revises: 7a4446c9936b
Create Date: 2024-09-08 05:14:24.496743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e29ddb3e5d'
down_revision: Union[str, None] = '7a4446c9936b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invite_email', table_name='invite')
    op.create_index(op.f('ix_invite_email'), 'invite', ['email'], unique=False)
    op.drop_constraint('invite_inviter_id_fkey', 'invite', type_='foreignkey')
    op.drop_constraint('invite_group_id_fkey', 'invite', type_='foreignkey')
    op.create_foreign_key('invite_inviter_id_fkey', 'invite', 'user', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invite_group_id_fkey', 'invite', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invite_group_id_fkey', 'invite', type_='foreignkey')
    op.drop_constraint('invite_inviter_id_fkey', 'invite', type_='foreignkey')
    op.create_foreign_key('invite_group_id_fkey', 'invite', 'group', ['group_id'], ['id'])
    op.create_foreign_key('invite_inviter_id_fkey', 'invite', 'user', ['inviter_id'], ['id'])
    op.drop_index(op.f('ix_invite_email'), table_name='invite')
    op.create_index('ix_invite_email', 'invite', ['email'], unique=True)
    # ### end Alembic commands ###
