"""add inbox item

Revision ID: dba1e8d3b15a
Revises: d4e8b2a91c07
Create Date: 2026-10-07 05:42:24.533861

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dba1e8d3b15a"
down_revision: Union[str, None] = "d4e8b2a91c07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("target_api_id", sa.String(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="inbox_item_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbox_item_api_identifier"),
        "inbox_item",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_inbox_item_created_at"),
        "inbox_item",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbox_item_id"), "inbox_item", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_inbox_item_user_id"), "inbox_item", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbox_item_user_id"), table_name="inbox_item")
    op.drop_index(op.f("ix_inbox_item_id"), table_name="inbox_item")
    op.drop_index(op.f("ix_inbox_item_created_at"), table_name="inbox_item")
    op.drop_index(
        op.f("ix_inbox_item_api_identifier"), table_name="inbox_item"
    )
    op.drop_table("inbox_item")
    # ### end Alembic commands ###
