"""add status and sent columns to letter

Revision ID: e33eb3e58a8a
Revises: 594ebed9b95e
Create Date: 2024-06-22 07:49:39.667031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e33eb3e58a8a"
down_revision: Union[str, None] = "594ebed9b95e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("letter", sa.Column("status", sa.String(), nullable=True))
    op.add_column(
        "letter", sa.Column("issue_sent", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("letter", "issue_sent")
    op.drop_column("letter", "status")
    # ### end Alembic commands ###
