"""add search association table

Revision ID: e66b58976126
Revises: 91b4bcfe36a1
Create Date: 2025-05-21 00:33:06.653139

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e66b58976126"
down_revision: Union[str, None] = "91b4bcfe36a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database to this migration version.

    Implements the forward migration by applying schema changes and data
    transformations to reach this version from the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hybrid_search_document_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hybrid_search_document_id", sa.Integer(), nullable=False),
        sa.Column("model_api_identifier", sa.String(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hybrid_search_document_id"],
            ["hybrid_search_document.id"],
            name="association_hybrid_search_document_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_api_identifier",
            "model_type",
            name="uq_model_api_identifier_model_type",
        ),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database from this migration version.

    Implements the reverse migration by reverting schema changes and data
    transformations to return to the previous version.

    Raises:
        sqlalchemy.exc.SQLAlchemyError: If the migration fails
        alembic.util.CommandError: If the migration configuration is invalid
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        "hybrid_search_document_association",
        if_exists=True,
    )
    # ### end Alembic commands ###
