"""add subscription table for notifications

Revision ID: eb62d542fc1a
Revises: 76581aa06774
Create Date: 2025-01-30 03:30:22.841635

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb62d542fc1a"
down_revision: Union[str, None] = "76581aa06774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column(
            "keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_identifier", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="subscription_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_api_identifier"),
        "subscription",
        ["api_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_created_at"),
        "subscription",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_endpoint"),
        "subscription",
        ["endpoint"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_id"), "subscription", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_subscription_user_id"),
        "subscription",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_user_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_endpoint"), table_name="subscription")
    op.drop_index(
        op.f("ix_subscription_created_at"), table_name="subscription"
    )
    op.drop_index(
        op.f("ix_subscription_api_identifier"), table_name="subscription"
    )
    op.drop_table("subscription")
    # ### end Alembic commands ###
