/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as MaintenanceImport } from './routes/maintenance'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as ResetPasswordTokenImport } from './routes/reset-password_/$token'
import { Route as RegisterTokenImport } from './routes/register/$token'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutSearchImport } from './routes/_layout/search'
import { Route as LayoutGroupsImport } from './routes/_layout/groups'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutSTokenImport } from './routes/_layout/s/$token'
import { Route as LayoutLoopsLoopIdImport } from './routes/_layout/loops/$loopId'
import { Route as LayoutDocumentsDocumentIdImport } from './routes/_layout/documents/$documentId'
import { Route as LayoutGroupsGroupIdSettingsImport } from './routes/_layout/groups_/$groupId/settings'
import { Route as LayoutGroupsGroupIdLoopsImport } from './routes/_layout/groups_/$groupId/loops'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const MaintenanceRoute = MaintenanceImport.update({
  path: '/maintenance',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const ResetPasswordTokenRoute = ResetPasswordTokenImport.update({
  path: '/reset-password/$token',
  getParentRoute: () => rootRoute,
} as any)

const RegisterTokenRoute = RegisterTokenImport.update({
  path: '/register/$token',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchRoute = LayoutSearchImport.update({
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGroupsRoute = LayoutGroupsImport.update({
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSTokenRoute = LayoutSTokenImport.update({
  path: '/s/$token',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoopsLoopIdRoute = LayoutLoopsLoopIdImport.update({
  path: '/loops/$loopId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDocumentsDocumentIdRoute = LayoutDocumentsDocumentIdImport.update({
  path: '/documents/$documentId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGroupsGroupIdSettingsRoute =
  LayoutGroupsGroupIdSettingsImport.update({
    path: '/groups/$groupId/settings',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutGroupsGroupIdLoopsRoute = LayoutGroupsGroupIdLoopsImport.update({
  path: '/groups/$groupId/loops',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/maintenance': {
      preLoaderRoute: typeof MaintenanceImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/groups': {
      preLoaderRoute: typeof LayoutGroupsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search': {
      preLoaderRoute: typeof LayoutSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/register/$token': {
      preLoaderRoute: typeof RegisterTokenImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/$token': {
      preLoaderRoute: typeof ResetPasswordTokenImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/documents/$documentId': {
      preLoaderRoute: typeof LayoutDocumentsDocumentIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/loops/$loopId': {
      preLoaderRoute: typeof LayoutLoopsLoopIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/s/$token': {
      preLoaderRoute: typeof LayoutSTokenImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/groups/$groupId/loops': {
      preLoaderRoute: typeof LayoutGroupsGroupIdLoopsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/groups/$groupId/settings': {
      preLoaderRoute: typeof LayoutGroupsGroupIdSettingsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutGroupsRoute,
    LayoutSearchRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutDocumentsDocumentIdRoute,
    LayoutLoopsLoopIdRoute,
    LayoutSTokenRoute,
    LayoutGroupsGroupIdLoopsRoute,
    LayoutGroupsGroupIdSettingsRoute,
  ]),
  LoginRoute,
  MaintenanceRoute,
  ResetPasswordRoute,
  RegisterTokenRoute,
  ResetPasswordTokenRoute,
])

/* prettier-ignore-end */
