# coding: utf-8

"""
    LLM Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from llm_service.api.completions_api import CompletionsApi


class TestCompletionsApi(unittest.TestCase):
    """CompletionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompletionsApi()

    def tearDown(self) -> None:
        pass

    def test_generate_completion_completions_generate_post(self) -> None:
        """Test case for generate_completion_completions_generate_post

        Generate Completion
        """
        pass

    def test_test_completion_completions_test_post(self) -> None:
        """Test case for test_completion_completions_test_post

        Test Completion
        """
        pass


if __name__ == '__main__':
    unittest.main()
