# coding: utf-8

"""
LLM Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import unittest

from llm_service.models.rag_request import RAGRequest


class TestRAGRequest(unittest.TestCase):
    """RAGRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RAGRequest:
        """Test RAGRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RAGRequest`
        """
        model = RAGRequest()
        if include_optional:
            return RAGRequest(
                query = '',
                context_window = 56
            )
        else:
            return RAGRequest(
                query = '',
        )
        """

    def testRAGRequest(self):
        """Test RAGRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
