# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from llm_service.api.embeddings_api import EmbeddingsApi


class TestEmbeddingsApi(unittest.TestCase):
    """EmbeddingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmbeddingsApi()

    def tearDown(self) -> None:
        pass

    def test_embed_embeddings_embed_post(self) -> None:
        """Test case for embed_embeddings_embed_post

        Embed
        """
        pass

    def test_test_completion_embeddings_test_post(self) -> None:
        """Test case for test_completion_embeddings_test_post

        Test Completion
        """
        pass


if __name__ == "__main__":
    unittest.main()
