# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from llm_service.models.embedding_response import EmbeddingResponse


class TestEmbeddingResponse(unittest.TestCase):
    """EmbeddingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbeddingResponse:
        """Test EmbeddingResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EmbeddingResponse`
        """
        model = EmbeddingResponse()
        if include_optional:
            return EmbeddingResponse(
                embedding = [
                    1.337
                    ]
            )
        else:
            return EmbeddingResponse(
                embedding = [
                    1.337
                    ],
        )
        """

    def testEmbeddingResponse(self):
        """Test EmbeddingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
