# coding: utf-8

"""
LLM Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from llm_service.api.rag_api import RagApi


class TestRagApi(unittest.TestCase):
    """RagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RagApi()

    def tearDown(self) -> None:
        pass

    def test_query_rag_rag_query_post(self) -> None:
        """Test case for query_rag_rag_query_post

        Query Rag
        """
        pass


if __name__ == "__main__":
    unittest.main()
