# coding: utf-8

"""
LLM Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from llm_service.models.completion_response import CompletionResponse


class TestCompletionResponse(unittest.TestCase):
    """CompletionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompletionResponse:
        """Test CompletionResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CompletionResponse`
        """
        model = CompletionResponse()
        if include_optional:
            return CompletionResponse(
                text = '',
                usage = llm_service.models.usage.Usage()
            )
        else:
            return CompletionResponse(
                text = '',
                usage = llm_service.models.usage.Usage(),
        )
        """

    def testCompletionResponse(self):
        """Test CompletionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
