"""API endpoints for managing LLM completions.

This module provides endpoints for managing LLM completions, allowing users to
generate text completions.
"""

from __future__ import annotations

import json

from fastapi import APIRouter, Depends
from llm_service import (
    ApiClient,
    CompletionsApi,
)
from llm_service import (
    CompletionRequest as LLMCompletionRequest,
)
from loguru import logger
from pydantic import BaseModel

from ring.fastapp.config import get_llm_config
from ring.fastapp.dependencies import (
    AuthenticatedRequestDependencies,
    get_request_dependencies,
)
from ring.llm.schemas.completion import CompletionRequest, CompletionResponse

router = APIRouter()


@router.post("/completion", response_model=CompletionResponse)
async def generate_completion(
    completion_request: CompletionRequest,
    req_dep: AuthenticatedRequestDependencies = Depends(
        get_request_dependencies,
    ),
) -> CompletionResponse:
    """Generate a completion for the given request.

    Generates a completion for the given request.

    Args:
        completion_request (CompletionRequest): Completion request details
        req_dep (AuthenticatedRequestDependencies): Request dependencies including database session

    Returns:
        CompletionResponse: Completion response details

    Raises:
        HTTPException: If user is not authenticated
    """

    api_client = ApiClient(configuration=get_llm_config().config)
    api_instance = CompletionsApi(api_client)

    system_prompt = f"""
    You are a helpful assistant for a private newsletter service used by a group of friends. 
    The newsletter is sent to the group on a regular basis, and is made up of a series of questions and responses
    that are generated by the users.

    You are a chatbot that is used to generate responses to any prompts that you may receive.
    You should always respond in the same language as the prompt.
    You should always respond in the same tone as the prompt.
    You should always respond in the same style as the prompt.
    You should always respond in the same format as the prompt.
    You should always respond in the same structure as the prompt.
    """

    user_information = str(req_dep.current_user.name)

    user_information_prompt = f"""
    Here is some information about the user that is requesting the completion:
    {user_information}

    You are not required to use this information, but it may be helpful if it is relevant to the prompt.
    """

    user_prompt = f"""
    Here is the prompt that the user has sent:
    {completion_request.prompt}

    Please construct a response to the prompt that is relevant and interesting to the user.
    """

    compiled_prompt = user_information_prompt + user_prompt

    class OutputFormat(BaseModel):
        response: str

    completion_request = LLMCompletionRequest(
        prompt=compiled_prompt,
        output_schema_definition=json.dumps(OutputFormat.model_json_schema()),
    )

    logger.info(f"Completion Request: {completion_request}")

    response = api_instance.generate_completion_completions_generate_post(
        completion_request
    )

    logger.info(f"Completion Response: {response}")
    output = OutputFormat.model_validate_json(response.output_schema)

    return CompletionResponse(text=output.response)
