// This file is auto-generated by @hey-api/openapi-ts

/**
 * Schema for adding members to a group.
 *
 * Attributes:
 * member_emails (list[str]): List of email addresses to invite
 */
export type AddMembers = {
    member_emails: Array<string>;
};

export type BodyLoginAccessTokenLoginAccessTokenPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyUploadImageQuestionsQuestionQuestionApiIdUploadImagePost = {
    response_image: Blob | File;
};

export type BodyUploadImageResponsesResponseResponseApiIdUploadImagePost = {
    response_images: Array<Blob | File>;
};

/**
 * Schema for bulk updating multiple key-value pairs.
 *
 * This model allows multiple key-value operations to be performed in a single request.
 * Each update in the list can be either a 'set' or 'delete' operation.
 *
 * Attributes:
 * updates (list[SingleGroupKeyValueUpdate]): List of update operations to perform
 *
 * Note:
 * At least one update operation must be provided
 */
export type BulkGroupKeyValueUpdate = {
    /**
     * List of key-value update operations to perform
     */
    updates: Array<SingleGroupKeyValueUpdate>;
};

export type CompletionRequest = {
    prompt: string;
};

export type CompletionResponse = {
    text: string;
};

/**
 * Model for the letters dashboard view.
 *
 * Groups letters by their status for dashboard display.
 *
 * Attributes:
 * upcoming (list[PublicLetter]): Letters scheduled for the future
 * in_progress (list[PublicLetter]): Currently active letters
 * recently_completed (list[PublicLetter]): Recently finished letters
 */
export type DashboardLetters = {
    upcoming: Array<PublicLetter>;
    in_progress: Array<PublicLetter>;
    recently_completed: Array<PublicLetter>;
};

export type GenerateQuestionRequest = {
    prompt: string;
};

export type GenerateQuestionResponse = {
    generated_text: string;
};

/**
 * Schema for creating a new group.
 *
 * Attributes:
 * name (str): Name of the group (inherited from GroupBase)
 * admin_api_identifier (str): API identifier of the user who will be admin
 */
export type GroupCreate = {
    name: string;
    admin_api_identifier: string;
};

/**
 * Schema for group key-value responses.
 *
 * This model represents the complete key-value store for a group, containing
 * all key-value pairs in a dictionary format.
 *
 * Attributes:
 * key_values (dict[str, Any]): Dictionary containing all key-value pairs for the group
 */
export type GroupKeyValue = {
    /**
     * Dictionary containing all key-value pairs for the group
     */
    key_values: {
        [key: string]: unknown;
    };
};

/**
 * Base schema for group key-value operations.
 *
 * This is the base model that defines the fundamental structure of a key-value pair.
 * It is used as a building block for other key-value related schemas.
 *
 * Attributes:
 * key (str): The key identifier for the value
 * value (Any): The value associated with the key, can be any JSON-serializable type
 */
export type GroupKeyValueBase = {
    /**
     * The key identifier for the value
     */
    key: string;
    /**
     * The value associated with the key
     */
    value: unknown;
};

/**
 * Group model with linked relationships.
 *
 * Extends the base Group model to include members, letters, and other related data.
 *
 * Attributes:
 * members (list[UserUnlinked]): Users who are members of the group
 * letters (list[LetterUnlinked]): Letters associated with the group
 * schedule (Optional[ScheduleUnlinked]): Group's schedule, if any
 * admin (UserUnlinked): The group administrator
 * default_questions (list[QuestionUnlinked]): Default questions for group letters
 */
export type GroupLinked = {
    name: string;
    api_identifier: string;
    created_at: string;
    cycle_length: number;
    members: Array<UserUnlinked>;
    letters: Array<LetterUnlinked>;
    schedule: ScheduleUnlinked | null;
    admin: UserUnlinked;
    default_questions: Array<QuestionUnlinked>;
};

/**
 * Schema for groups without linked relationships.
 *
 * Inherits all fields from Group but excludes relationship data.
 */
export type GroupUnlinked = {
    name: string;
    api_identifier: string;
    created_at: string;
    cycle_length: number;
};

/**
 * Schema for updating an existing group.
 *
 * Attributes:
 * name (str | None): New name for the group, optional
 * cycle_length (int | None): New cycle length in days, optional
 */
export type GroupUpdate = {
    name?: string | null;
    cycle_length?: number | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Schema for image data.
 *
 * Represents an image stored in S3 with its media type.
 *
 * Attributes:
 * s3_url (str): S3 key/path for the image
 * media_type (MediaType): Type of media (image/video)
 */
export type Image = {
    s3_url: string;
    media_type: MediaType;
};

/**
 * Schema for creating a new invite.
 *
 * Attributes:
 * email (str): Email address of the invitee (inherited from InviteBase)
 * group_api_id (str): API identifier of the group to invite to
 */
export type InviteCreate = {
    email: string;
    group_api_id: string;
};

/**
 * Invite model with linked relationships.
 *
 * Extends the base Invite model to include inviter and group information.
 *
 * Attributes:
 * inviter (UserUnlinked): User who created the invite
 * group (GroupUnlinked): Group the invite is for
 */
export type InviteLinked = {
    email: string;
    api_identifier: string;
    created_at: string;
    inviter: UserUnlinked;
    group: GroupUnlinked;
    /**
     * Get the token string.
     *
     * :return: Token string
     * :rtype: str
     */
    readonly token: string;
    /**
     * Check if the token has expired.
     *
     * :return: True if expired, False otherwise
     * :rtype: bool
     */
    readonly is_expired: boolean;
};

/**
 * Schema for creating a new letter.
 *
 * Attributes:
 * group_api_identifier (str): API identifier of the group to create the letter for
 * send_at (AwareDatetime): Scheduled time to send the letter
 */
export type LetterCreate = {
    group_api_identifier: string;
    send_at: string;
};

/**
 * Letter model with linked relationships.
 *
 * Extends the base Letter model to include participants, group, and questions.
 *
 * Attributes:
 * participants (list[UserUnlinked]): Users participating in the letter
 * group (GroupUnlinked): Group the letter belongs to
 * questions (list[QuestionLinked]): Questions in the letter
 */
export type LetterLinked = {
    api_identifier: string;
    number: number;
    status: LetterStatus;
    send_at: string;
    created_at: string;
    participants: Array<UserUnlinked>;
    group: GroupUnlinked;
    questions: Array<QuestionLinked>;
};

/**
 * Enumeration of possible letter statuses.
 * Represents the different states a letter can be in within the system:
 * - UPCOMING: Letter is scheduled but not yet active
 * - IN_PROGRESS: Letter is currently active and accepting responses
 * - SENT: Letter has been completed and sent
 */
export type LetterStatus = 'UPCOMING' | 'IN_PROGRESS' | 'SENT';

/**
 * Schema for letter without linked relationships.
 *
 * Inherits all fields from Letter but excludes relationship data.
 */
export type LetterUnlinked = {
    api_identifier: string;
    number: number;
    status: LetterStatus;
    send_at: string;
    created_at: string;
};

/**
 * Schema for updating an existing letter.
 *
 * Attributes:
 * send_at (AwareDatetime): New scheduled time to send the letter
 */
export type LetterUpdate = {
    send_at: string;
};

/**
 * Enumeration of supported media types.
 *
 * Attributes:
 * IMAGE: Image files (e.g., jpg, png)
 * VIDEO: Video files
 */
export type MediaType = 'image' | 'video';

/**
 * Schema for setting a new password (e.g., after reset).
 *
 * Attributes:
 * new_password (str): User's new password
 */
export type NewPassword = {
    new_password: string;
};

/**
 * Public letter model with linked relationships.
 *
 * A version of the Letter model that includes public information about participants
 * and responses.
 *
 * Attributes:
 * group (GroupUnlinked): Group the letter belongs to
 * questions (list[PublicQuestion]): Questions with public responses
 * responders (list[UserUnlinked]): Users who have responded
 * participants (list[UserUnlinked]): All participants in the letter
 */
export type PublicLetter = {
    api_identifier: string;
    number: number;
    status: LetterStatus;
    send_at: string;
    created_at: string;
    group: GroupUnlinked;
    questions: Array<PublicQuestion>;
    responders: Array<UserUnlinked>;
    participants: Array<UserUnlinked>;
};

/**
 * Public question model with linked relationships.
 *
 * A version of the Question model that includes public response information.
 *
 * Attributes:
 * responses (list[ResponseWithParticipant]): Public responses with participant info
 * author (Optional[UserUnlinked]): Question author, if available
 */
export type PublicQuestion = {
    question_text: string;
    api_identifier: string;
    created_at: string;
    responses: Array<ResponseWithParticipant>;
    author: UserUnlinked | null;
};

/**
 * Schema for creating a new question.
 *
 * Attributes:
 * question_text (str): The text content of the question
 * author_api_id (str | None): API identifier of the question's author, optional
 */
export type QuestionCreate = {
    question_text: string;
    author_api_id: string | null;
};

/**
 * Question model with linked relationships.
 *
 * Extends the base Question model to include the parent letter and responses.
 *
 * Attributes:
 * letter (LetterUnlinked): Letter containing this question
 * responses (list[ResponseUnlinked]): Responses to this question
 */
export type QuestionLinked = {
    question_text: string;
    api_identifier: string;
    created_at: string;
    letter: LetterUnlinked;
    responses: Array<ResponseUnlinked>;
};

/**
 * Schema for question without linked relationships.
 *
 * Inherits all fields from Question but excludes relationship data.
 */
export type QuestionUnlinked = {
    question_text: string;
    api_identifier: string;
    created_at: string;
};

export type RawSearchResponse = {
    results: Array<RawSearchResult>;
    total: number;
};

export type RawSearchResult = {
    raw_text: string;
};

/**
 * Schema for replacing a group's default questions.
 *
 * Attributes:
 * questions (list[str]): New list of default questions
 */
export type ReplaceDefaultQuestions = {
    questions: Array<string>;
};

/**
 * Base schema for response creation operations.
 *
 * Inherits response_text field from ResponseBase.
 */
export type ResponseCreateBase = {
    response_text: string;
};

/**
 * Response model with linked relationships and image support.
 *
 * Extends the base Response model to include question and participant info,
 * with support for attached images.
 *
 * Attributes:
 * question (QuestionUnlinked): Question this response is for
 * participant (UserUnlinked): User who provided the response
 */
export type ResponseLinked = {
    response_text: string;
    api_identifier: string;
    created_at: string;
    question: QuestionUnlinked;
    participant: UserUnlinked;
    letter: LetterUnlinked;
    group: GroupUnlinked;
    /**
     * Get the list of images associated with this model.
     *
     * Returns:
     * list[Image]: List of associated images
     */
    readonly images: Array<Image>;
};

/**
 * Standard response message model.
 *
 * Used for API endpoints that return a simple message response.
 *
 * Attributes:
 * message (str): The response message text
 */
export type ResponseMessage = {
    message: string;
};

/**
 * Schema for response without linked relationships.
 *
 * Inherits all fields from Response but excludes relationship data.
 */
export type ResponseUnlinked = {
    response_text: string;
    api_identifier: string;
    created_at: string;
};

/**
 * Schema for creating or updating a response.
 *
 * Attributes:
 * response_text (str): The text content of the response
 * participant_api_identifier (Optional[str]): API identifier of the participant, optional
 * api_identifier (Optional[str]): API identifier of an existing response, optional
 */
export type ResponseUpsert = {
    response_text: string;
    participant_api_identifier?: string | null;
    api_identifier?: string | null;
};

/**
 * Response model with participant information and image support.
 *
 * A version of the Response model that includes participant information
 * and support for attached images.
 *
 * Attributes:
 * participant (UserUnlinked): User who provided the response
 */
export type ResponseWithParticipant = {
    response_text: string;
    api_identifier: string;
    created_at: string;
    participant: UserUnlinked;
    /**
     * Get the list of images associated with this model.
     *
     * Returns:
     * list[Image]: List of associated images
     */
    readonly images: Array<Image>;
};

/**
 * Schedule model with linked relationships.
 *
 * Extends the base Schedule model to include the associated group and tasks.
 *
 * Attributes:
 * group (GroupUnlinked): The group this schedule belongs to
 * tasks (list[TaskUnlinked]): Tasks in the schedule
 */
export type ScheduleLinked = {
    group: GroupUnlinked;
    tasks: Array<TaskUnlinked>;
};

/**
 * Parameters for scheduling a send operation.
 *
 * This schema defines the parameters needed to schedule a send operation
 * for a letter.
 *
 * Attributes:
 * letter_api_id: API identifier of the letter to send
 * send_at: When the letter should be sent
 */
export type ScheduleSendParam = {
    letter_api_id: string;
    send_at: string;
};

/**
 * Schema for schedule data with unlinked task relationships.
 *
 * This schema extends the base Schedule schema and includes a list of tasks,
 * using the unlinked task schema to avoid circular references.
 *
 * Attributes:
 * tasks: List of tasks associated with this schedule
 */
export type ScheduleUnlinked = {
    tasks: Array<TaskUnlinked>;
};

export type SearchResponse = {
    results: Array<SearchResult>;
    total: number;
};

/**
 * Search result model that can hold different types of models based on type field.
 *
 * Attributes:
 * model (Any): The model instance
 * type (str): The type of the model
 */
export type SearchResult = {
    model: UserLinked | GroupLinked | QuestionLinked | LetterLinked | ResponseLinked;
    type: string;
};

export type SearchType = 'semantic' | 'keyword' | 'dual';

/**
 * Schema for updating a single group key-value pair.
 *
 * This model extends GroupKeyValueBase to include an operation field that specifies
 * whether to set or delete the key-value pair.
 *
 * Attributes:
 * key (str): The key identifier to update
 * value (Any | None): The value to set (required for 'set' operation, ignored for 'delete')
 * operation (Literal["set", "delete"]): The operation to perform on the key-value pair
 *
 * Note:
 * For 'delete' operations, the value field is ignored
 */
export type SingleGroupKeyValueUpdate = {
    /**
     * The key identifier for the value
     */
    key: string;
    /**
     * Value to set (required for 'set' operation, ignored for 'delete')
     */
    value?: unknown | null;
    /**
     * Operation to perform: 'set' to update/create, 'delete' to remove
     */
    operation: 'set' | 'delete';
};

/**
 * Schema for creating a new subscription.
 *
 * Inherits endpoint and keys from SubscriptionBase and adds user identification.
 *
 * Attributes:
 * endpoint (str): Push notification endpoint URL
 * keys (dict[str, str | float | bool]): Dictionary containing encryption keys and auth info
 * user_api_identifier (str): API identifier of the user to subscribe
 */
export type SubscriptionCreate = {
    endpoint: string;
    keys: {
        [key: string]: string | number | boolean;
    };
    user_api_identifier: string;
};

/**
 * Schema for task data without linked relationships.
 *
 * This schema extends the base Task schema but excludes any linked relationships,
 * useful for nested serialization to avoid circular references.
 */
export type TaskUnlinked = {
    type: string;
    status: string;
    execute_at: string;
    arguments: {
        [key: string]: string;
    };
};

/**
 * Authentication token schema.
 *
 * Represents the structure of an authentication token response.
 *
 * Attributes:
 * access_token (str): The JWT access token string
 * token_type (str): The type of token (e.g., "bearer")
 */
export type Token = {
    access_token: string;
    token_type: string;
};

/**
 * Schema for creating a new user.
 *
 * Attributes:
 * email (str): User's email address (inherited from UserBase)
 * name (str): User's display name (inherited from UserBase)
 * password (str): User's password (will be hashed)
 */
export type UserCreate = {
    email: string;
    name: string;
    password: string;
};

/**
 * User model with linked relationships.
 *
 * Extends the base User model to include related groups and responses.
 *
 * Attributes:
 * groups (list[GroupUnlinked]): Groups the user is a member of
 * responses (list[ResponseUnlinked]): User's responses to questions
 */
export type UserLinked = {
    email: string;
    name: string;
    api_identifier: string;
    admin: boolean;
    groups: Array<GroupUnlinked>;
    responses: Array<ResponseUnlinked>;
};

/**
 * Schema for users without linked relationships.
 *
 * Inherits all fields from User but excludes relationship data.
 */
export type UserUnlinked = {
    email: string;
    name: string;
    api_identifier: string;
    admin: boolean;
};

/**
 * Schema for updating an existing user.
 *
 * Attributes:
 * email (str | None): New email address, optional
 * name (str | None): New display name, optional
 */
export type UserUpdate = {
    email?: string | null;
    name?: string | null;
};

/**
 * Schema for updating a user's password.
 *
 * Attributes:
 * current_password (str): User's current password
 * new_password (str): User's new password
 */
export type UserUpdatePassword = {
    current_password: string;
    new_password: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type LoginAccessTokenLoginAccessTokenPostData = {
    body: BodyLoginAccessTokenLoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/login/access-token';
};

export type LoginAccessTokenLoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenLoginAccessTokenPostError = LoginAccessTokenLoginAccessTokenPostErrors[keyof LoginAccessTokenLoginAccessTokenPostErrors];

export type LoginAccessTokenLoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenLoginAccessTokenPostResponse = LoginAccessTokenLoginAccessTokenPostResponses[keyof LoginAccessTokenLoginAccessTokenPostResponses];

export type ImpersonateUserTokenImpersonateUserTokenPostData = {
    body?: never;
    path?: never;
    query: {
        user_api_id: string;
    };
    url: '/impersonate-user-token';
};

export type ImpersonateUserTokenImpersonateUserTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImpersonateUserTokenImpersonateUserTokenPostError = ImpersonateUserTokenImpersonateUserTokenPostErrors[keyof ImpersonateUserTokenImpersonateUserTokenPostErrors];

export type ImpersonateUserTokenImpersonateUserTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type ImpersonateUserTokenImpersonateUserTokenPostResponse = ImpersonateUserTokenImpersonateUserTokenPostResponses[keyof ImpersonateUserTokenImpersonateUserTokenPostResponses];

export type TestTokenLoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/test-token';
};

export type TestTokenLoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type TestTokenLoginTestTokenPostResponse = TestTokenLoginTestTokenPostResponses[keyof TestTokenLoginTestTokenPostResponses];

export type ResetPasswordRequestResetPasswordRequestEmailPostData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/reset-password:request/{email}';
};

export type ResetPasswordRequestResetPasswordRequestEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordRequestResetPasswordRequestEmailPostError = ResetPasswordRequestResetPasswordRequestEmailPostErrors[keyof ResetPasswordRequestResetPasswordRequestEmailPostErrors];

export type ResetPasswordRequestResetPasswordRequestEmailPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type ResetPasswordRequestResetPasswordRequestEmailPostResponse = ResetPasswordRequestResetPasswordRequestEmailPostResponses[keyof ResetPasswordRequestResetPasswordRequestEmailPostResponses];

export type ResetPasswordResetPasswordTokenPostData = {
    body: NewPassword;
    path: {
        token: string;
    };
    query?: never;
    url: '/reset-password/{token}';
};

export type ResetPasswordResetPasswordTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordResetPasswordTokenPostError = ResetPasswordResetPasswordTokenPostErrors[keyof ResetPasswordResetPasswordTokenPostErrors];

export type ResetPasswordResetPasswordTokenPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type ResetPasswordResetPasswordTokenPostResponse = ResetPasswordResetPasswordTokenPostResponses[keyof ResetPasswordResetPasswordTokenPostResponses];

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/password-recovery-html-content/{email}';
};

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostError = RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostErrors[keyof RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostErrors];

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostResponse = RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostResponses[keyof RecoverPasswordHtmlContentPasswordRecoveryHtmlContentEmailPostResponses];

export type DeleteUserMePartiesMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties/me';
};

export type DeleteUserMePartiesMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type DeleteUserMePartiesMeDeleteResponse = DeleteUserMePartiesMeDeleteResponses[keyof DeleteUserMePartiesMeDeleteResponses];

export type ReadUserMePartiesMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties/me';
};

export type ReadUserMePartiesMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserLinked;
};

export type ReadUserMePartiesMeGetResponse = ReadUserMePartiesMeGetResponses[keyof ReadUserMePartiesMeGetResponses];

export type UpdateUserMePartiesMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/parties/me';
};

export type UpdateUserMePartiesMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMePartiesMePatchError = UpdateUserMePartiesMePatchErrors[keyof UpdateUserMePartiesMePatchErrors];

export type UpdateUserMePartiesMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserLinked;
};

export type UpdateUserMePartiesMePatchResponse = UpdateUserMePartiesMePatchResponses[keyof UpdateUserMePartiesMePatchResponses];

export type CreateUserPartiesUserPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/parties/user';
};

export type CreateUserPartiesUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserPartiesUserPostError = CreateUserPartiesUserPostErrors[keyof CreateUserPartiesUserPostErrors];

export type CreateUserPartiesUserPostResponses = {
    /**
     * Successful Response
     */
    201: UserLinked;
};

export type CreateUserPartiesUserPostResponse = CreateUserPartiesUserPostResponses[keyof CreateUserPartiesUserPostResponses];

export type RegisterUserPartiesRegisterTokenPostData = {
    body: UserCreate;
    path: {
        token: string;
    };
    query?: never;
    url: '/parties/register/{token}';
};

export type RegisterUserPartiesRegisterTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserPartiesRegisterTokenPostError = RegisterUserPartiesRegisterTokenPostErrors[keyof RegisterUserPartiesRegisterTokenPostErrors];

export type RegisterUserPartiesRegisterTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserLinked;
};

export type RegisterUserPartiesRegisterTokenPostResponse = RegisterUserPartiesRegisterTokenPostResponses[keyof RegisterUserPartiesRegisterTokenPostResponses];

export type ReadUsersPartiesUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/parties/users';
};

export type ReadUsersPartiesUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersPartiesUsersGetError = ReadUsersPartiesUsersGetErrors[keyof ReadUsersPartiesUsersGetErrors];

export type ReadUsersPartiesUsersGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserLinked>;
};

export type ReadUsersPartiesUsersGetResponse = ReadUsersPartiesUsersGetResponses[keyof ReadUsersPartiesUsersGetResponses];

export type ReadUserByIdPartiesUserUserApiIdGetData = {
    body?: never;
    path: {
        user_api_id: string;
    };
    query?: never;
    url: '/parties/user/{user_api_id}';
};

export type ReadUserByIdPartiesUserUserApiIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdPartiesUserUserApiIdGetError = ReadUserByIdPartiesUserUserApiIdGetErrors[keyof ReadUserByIdPartiesUserUserApiIdGetErrors];

export type ReadUserByIdPartiesUserUserApiIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserLinked;
};

export type ReadUserByIdPartiesUserUserApiIdGetResponse = ReadUserByIdPartiesUserUserApiIdGetResponses[keyof ReadUserByIdPartiesUserUserApiIdGetResponses];

export type UpdatePasswordMePartiesMePasswordPatchData = {
    body: UserUpdatePassword;
    path?: never;
    query?: never;
    url: '/parties/me/password';
};

export type UpdatePasswordMePartiesMePasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMePartiesMePasswordPatchError = UpdatePasswordMePartiesMePasswordPatchErrors[keyof UpdatePasswordMePartiesMePasswordPatchErrors];

export type UpdatePasswordMePartiesMePasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type UpdatePasswordMePartiesMePasswordPatchResponse = UpdatePasswordMePartiesMePasswordPatchResponses[keyof UpdatePasswordMePartiesMePasswordPatchResponses];

export type UpdateUserAdminPartiesUserApiIdAdminPatchData = {
    body?: never;
    path: {
        user_api_id: string;
    };
    query?: never;
    url: '/parties/{user_api_id}/admin';
};

export type UpdateUserAdminPartiesUserApiIdAdminPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserAdminPartiesUserApiIdAdminPatchError = UpdateUserAdminPartiesUserApiIdAdminPatchErrors[keyof UpdateUserAdminPartiesUserApiIdAdminPatchErrors];

export type UpdateUserAdminPartiesUserApiIdAdminPatchResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type UpdateUserAdminPartiesUserApiIdAdminPatchResponse = UpdateUserAdminPartiesUserApiIdAdminPatchResponses[keyof UpdateUserAdminPartiesUserApiIdAdminPatchResponses];

export type SignupPartiesSignupPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties/signup';
};

export type SignupPartiesSignupPostResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type SignupPartiesSignupPostResponse = SignupPartiesSignupPostResponses[keyof SignupPartiesSignupPostResponses];

export type DeleteUserPartiesUserIdDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties/{user_id}';
};

export type DeleteUserPartiesUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type DeleteUserPartiesUserIdDeleteResponse = DeleteUserPartiesUserIdDeleteResponses[keyof DeleteUserPartiesUserIdDeleteResponses];

export type UpdateUserPartiesUserIdPatchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/parties/{user_id}';
};

export type UpdateUserPartiesUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: null;
};

export type UpdateUserPartiesUserIdPatchResponse = UpdateUserPartiesUserIdPatchResponses[keyof UpdateUserPartiesUserIdPatchResponses];

export type CreateGroupPartiesGroupPostData = {
    body: GroupCreate;
    path?: never;
    query?: never;
    url: '/parties/group';
};

export type CreateGroupPartiesGroupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupPartiesGroupPostError = CreateGroupPartiesGroupPostErrors[keyof CreateGroupPartiesGroupPostErrors];

export type CreateGroupPartiesGroupPostResponses = {
    /**
     * Successful Response
     */
    201: GroupLinked;
};

export type CreateGroupPartiesGroupPostResponse = CreateGroupPartiesGroupPostResponses[keyof CreateGroupPartiesGroupPostResponses];

export type ListGroupsPartiesGroupsGetData = {
    body?: never;
    path?: never;
    query: {
        user_api_id: string;
        skip?: number;
        limit?: number;
    };
    url: '/parties/groups/';
};

export type ListGroupsPartiesGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGroupsPartiesGroupsGetError = ListGroupsPartiesGroupsGetErrors[keyof ListGroupsPartiesGroupsGetErrors];

export type ListGroupsPartiesGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<GroupLinked>;
};

export type ListGroupsPartiesGroupsGetResponse = ListGroupsPartiesGroupsGetResponses[keyof ListGroupsPartiesGroupsGetResponses];

export type ReadGroupPartiesGroupGroupApiIdGetData = {
    body?: never;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}';
};

export type ReadGroupPartiesGroupGroupApiIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupPartiesGroupGroupApiIdGetError = ReadGroupPartiesGroupGroupApiIdGetErrors[keyof ReadGroupPartiesGroupGroupApiIdGetErrors];

export type ReadGroupPartiesGroupGroupApiIdGetResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type ReadGroupPartiesGroupGroupApiIdGetResponse = ReadGroupPartiesGroupGroupApiIdGetResponses[keyof ReadGroupPartiesGroupGroupApiIdGetResponses];

export type UpdateGroupPartiesGroupGroupApiIdPatchData = {
    body: GroupUpdate;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}';
};

export type UpdateGroupPartiesGroupGroupApiIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupPartiesGroupGroupApiIdPatchError = UpdateGroupPartiesGroupGroupApiIdPatchErrors[keyof UpdateGroupPartiesGroupGroupApiIdPatchErrors];

export type UpdateGroupPartiesGroupGroupApiIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type UpdateGroupPartiesGroupGroupApiIdPatchResponse = UpdateGroupPartiesGroupGroupApiIdPatchResponses[keyof UpdateGroupPartiesGroupGroupApiIdPatchResponses];

export type AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostData = {
    body?: never;
    path: {
        group_api_id: string;
        user_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}:add_member/{user_api_id}';
};

export type AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostError = AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostErrors[keyof AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostErrors];

export type AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostResponse = AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostResponses[keyof AddUserToGroupPartiesGroupGroupApiIdAddMemberUserApiIdPostResponses];

export type RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostData = {
    body?: never;
    path: {
        group_api_id: string;
        user_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}:remove_member/{user_api_id}';
};

export type RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostError = RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostErrors[keyof RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostErrors];

export type RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostResponse = RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostResponses[keyof RemoveUserFromGroupPartiesGroupGroupApiIdRemoveMemberUserApiIdPostResponses];

export type ScheduleSendPartiesGroupGroupApiIdScheduleSendPostData = {
    body: ScheduleSendParam;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}:schedule_send';
};

export type ScheduleSendPartiesGroupGroupApiIdScheduleSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduleSendPartiesGroupGroupApiIdScheduleSendPostError = ScheduleSendPartiesGroupGroupApiIdScheduleSendPostErrors[keyof ScheduleSendPartiesGroupGroupApiIdScheduleSendPostErrors];

export type ScheduleSendPartiesGroupGroupApiIdScheduleSendPostResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type ScheduleSendPartiesGroupGroupApiIdScheduleSendPostResponse = ScheduleSendPartiesGroupGroupApiIdScheduleSendPostResponses[keyof ScheduleSendPartiesGroupGroupApiIdScheduleSendPostResponses];

export type AddMembersPartiesGroupGroupApiIdAddMembersPostData = {
    body: AddMembers;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}:add_members';
};

export type AddMembersPartiesGroupGroupApiIdAddMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMembersPartiesGroupGroupApiIdAddMembersPostError = AddMembersPartiesGroupGroupApiIdAddMembersPostErrors[keyof AddMembersPartiesGroupGroupApiIdAddMembersPostErrors];

export type AddMembersPartiesGroupGroupApiIdAddMembersPostResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type AddMembersPartiesGroupGroupApiIdAddMembersPostResponse = AddMembersPartiesGroupGroupApiIdAddMembersPostResponses[keyof AddMembersPartiesGroupGroupApiIdAddMembersPostResponses];

export type ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostData = {
    body: ReplaceDefaultQuestions;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}:replace_default_questions';
};

export type ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostError = ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostErrors[keyof ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostErrors];

export type ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: GroupLinked;
};

export type ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostResponse = ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostResponses[keyof ReplaceGroupDefaultQuestionsPartiesGroupGroupApiIdReplaceDefaultQuestionsPostResponses];

export type ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetData = {
    body?: never;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}/key-value';
};

export type ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetError = ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetErrors[keyof ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetErrors];

export type ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetResponses = {
    /**
     * Successful Response
     */
    200: GroupKeyValue;
};

export type ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetResponse = ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetResponses[keyof ReadGroupKeyValuesPartiesGroupGroupApiIdKeyValueGetResponses];

export type FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutData = {
    body: GroupKeyValue;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}/key-value';
};

export type FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutError = FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutErrors[keyof FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutErrors];

export type FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutResponses = {
    /**
     * Successful Response
     */
    200: GroupKeyValue;
};

export type FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutResponse = FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutResponses[keyof FullReplaceGroupKeyValuesPartiesGroupGroupApiIdKeyValuePutResponses];

export type ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetData = {
    body?: never;
    path: {
        group_api_id: string;
        key: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}/key-value/{key}';
};

export type ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetError = ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetErrors[keyof ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetErrors];

export type ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetResponses = {
    /**
     * Successful Response
     */
    200: GroupKeyValueBase;
};

export type ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetResponse = ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetResponses[keyof ReadGroupKeyValuePartiesGroupGroupApiIdKeyValueKeyGetResponses];

export type UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostData = {
    body: SingleGroupKeyValueUpdate;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}/key-value:update';
};

export type UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostError = UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostErrors[keyof UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostErrors];

export type UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: GroupKeyValueBase;
};

export type UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostResponse = UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostResponses[keyof UpsertGroupKeyValuePartiesGroupGroupApiIdKeyValueUpdatePostResponses];

export type BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostData = {
    body: BulkGroupKeyValueUpdate;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/parties/group/{group_api_id}/key-value:bulk-update';
};

export type BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostError = BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostErrors[keyof BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostErrors];

export type BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostResponses = {
    /**
     * Successful Response
     */
    200: GroupKeyValue;
};

export type BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostResponse = BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostResponses[keyof BulkUpdateGroupKeyValuesPartiesGroupGroupApiIdKeyValueBulkUpdatePostResponses];

export type AddNextLetterLettersLetterPostData = {
    body: LetterCreate;
    path?: never;
    query?: never;
    url: '/letters/letter';
};

export type AddNextLetterLettersLetterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddNextLetterLettersLetterPostError = AddNextLetterLettersLetterPostErrors[keyof AddNextLetterLettersLetterPostErrors];

export type AddNextLetterLettersLetterPostResponses = {
    /**
     * Successful Response
     */
    200: PublicLetter;
};

export type AddNextLetterLettersLetterPostResponse = AddNextLetterLettersLetterPostResponses[keyof AddNextLetterLettersLetterPostResponses];

export type ListLettersLettersLettersGetData = {
    body?: never;
    path?: never;
    query: {
        group_api_id: string;
        skip?: number;
        limit?: number;
    };
    url: '/letters/letters/';
};

export type ListLettersLettersLettersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLettersLettersLettersGetError = ListLettersLettersLettersGetErrors[keyof ListLettersLettersLettersGetErrors];

export type ListLettersLettersLettersGetResponses = {
    /**
     * Successful Response
     */
    200: Array<PublicLetter>;
};

export type ListLettersLettersLettersGetResponse = ListLettersLettersLettersGetResponses[keyof ListLettersLettersLettersGetResponses];

export type ReadLetterLettersLetterLetterApiIdGetData = {
    body?: never;
    path: {
        letter_api_id: string;
    };
    query?: never;
    url: '/letters/letter/{letter_api_id}';
};

export type ReadLetterLettersLetterLetterApiIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadLetterLettersLetterLetterApiIdGetError = ReadLetterLettersLetterLetterApiIdGetErrors[keyof ReadLetterLettersLetterLetterApiIdGetErrors];

export type ReadLetterLettersLetterLetterApiIdGetResponses = {
    /**
     * Successful Response
     */
    200: PublicLetter;
};

export type ReadLetterLettersLetterLetterApiIdGetResponse = ReadLetterLettersLetterLetterApiIdGetResponses[keyof ReadLetterLettersLetterLetterApiIdGetResponses];

export type ListDashboardLettersLettersLettersDashboardGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/letters/letters:dashboard';
};

export type ListDashboardLettersLettersLettersDashboardGetResponses = {
    /**
     * Successful Response
     */
    200: DashboardLetters;
};

export type ListDashboardLettersLettersLettersDashboardGetResponse = ListDashboardLettersLettersLettersDashboardGetResponses[keyof ListDashboardLettersLettersLettersDashboardGetResponses];

export type EditLetterLettersLetterLetterApiIdEditLetterPostData = {
    body: LetterUpdate;
    path: {
        letter_api_id: string;
    };
    query?: never;
    url: '/letters/letter/{letter_api_id}:edit_letter';
};

export type EditLetterLettersLetterLetterApiIdEditLetterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditLetterLettersLetterLetterApiIdEditLetterPostError = EditLetterLettersLetterLetterApiIdEditLetterPostErrors[keyof EditLetterLettersLetterLetterApiIdEditLetterPostErrors];

export type EditLetterLettersLetterLetterApiIdEditLetterPostResponses = {
    /**
     * Successful Response
     */
    200: PublicLetter;
};

export type EditLetterLettersLetterLetterApiIdEditLetterPostResponse = EditLetterLettersLetterLetterApiIdEditLetterPostResponses[keyof EditLetterLettersLetterLetterApiIdEditLetterPostResponses];

export type AddQuestionLettersLetterLetterApiIdAddQuestionPostData = {
    body: QuestionCreate;
    path: {
        letter_api_id: string;
    };
    query?: never;
    url: '/letters/letter/{letter_api_id}:add_question';
};

export type AddQuestionLettersLetterLetterApiIdAddQuestionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddQuestionLettersLetterLetterApiIdAddQuestionPostError = AddQuestionLettersLetterLetterApiIdAddQuestionPostErrors[keyof AddQuestionLettersLetterLetterApiIdAddQuestionPostErrors];

export type AddQuestionLettersLetterLetterApiIdAddQuestionPostResponses = {
    /**
     * Successful Response
     */
    200: PublicLetter;
};

export type AddQuestionLettersLetterLetterApiIdAddQuestionPostResponse = AddQuestionLettersLetterLetterApiIdAddQuestionPostResponses[keyof AddQuestionLettersLetterLetterApiIdAddQuestionPostResponses];

export type GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostData = {
    body: GenerateQuestionRequest;
    path: {
        letter_api_id: string;
    };
    query?: never;
    url: '/letters/letter/{letter_api_id}:generate_question';
};

export type GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostError = GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostErrors[keyof GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostErrors];

export type GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostResponses = {
    /**
     * Successful Response
     */
    200: GenerateQuestionResponse;
};

export type GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostResponse = GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostResponses[keyof GenerateQuestionLettersLetterLetterApiIdGenerateQuestionPostResponses];

export type GetScheduleForGroupScheduleScheduleGroupApiIdGetData = {
    body?: never;
    path: {
        group_api_id: string;
    };
    query?: never;
    url: '/schedule/schedule/{group_api_id}';
};

export type GetScheduleForGroupScheduleScheduleGroupApiIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScheduleForGroupScheduleScheduleGroupApiIdGetError = GetScheduleForGroupScheduleScheduleGroupApiIdGetErrors[keyof GetScheduleForGroupScheduleScheduleGroupApiIdGetErrors];

export type GetScheduleForGroupScheduleScheduleGroupApiIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScheduleLinked;
};

export type GetScheduleForGroupScheduleScheduleGroupApiIdGetResponse = GetScheduleForGroupScheduleScheduleGroupApiIdGetResponses[keyof GetScheduleForGroupScheduleScheduleGroupApiIdGetResponses];

export type UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostData = {
    body: ResponseUpsert;
    path: {
        question_api_id: string;
    };
    query?: never;
    url: '/questions/question/{question_api_id}:upsert_response';
};

export type UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostError = UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostErrors[keyof UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostErrors];

export type UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostResponses = {
    /**
     * Successful Response
     */
    200: QuestionLinked;
};

export type UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostResponse = UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostResponses[keyof UpsertResponseQuestionsQuestionQuestionApiIdUpsertResponsePostResponses];

export type UploadImageQuestionsQuestionQuestionApiIdUploadImagePostData = {
    body: BodyUploadImageQuestionsQuestionQuestionApiIdUploadImagePost;
    path: {
        question_api_id: string;
    };
    query?: never;
    url: '/questions/question/{question_api_id}:upload_image';
};

export type UploadImageQuestionsQuestionQuestionApiIdUploadImagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageQuestionsQuestionQuestionApiIdUploadImagePostError = UploadImageQuestionsQuestionQuestionApiIdUploadImagePostErrors[keyof UploadImageQuestionsQuestionQuestionApiIdUploadImagePostErrors];

export type UploadImageQuestionsQuestionQuestionApiIdUploadImagePostResponses = {
    /**
     * Successful Response
     */
    200: QuestionLinked;
};

export type UploadImageQuestionsQuestionQuestionApiIdUploadImagePostResponse = UploadImageQuestionsQuestionQuestionApiIdUploadImagePostResponses[keyof UploadImageQuestionsQuestionQuestionApiIdUploadImagePostResponses];

export type DeleteQuestionQuestionsQuestionQuestionApiIdDeleteData = {
    body?: never;
    path: {
        question_api_id: string;
    };
    query?: never;
    url: '/questions/question/{question_api_id}';
};

export type DeleteQuestionQuestionsQuestionQuestionApiIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestionQuestionsQuestionQuestionApiIdDeleteError = DeleteQuestionQuestionsQuestionQuestionApiIdDeleteErrors[keyof DeleteQuestionQuestionsQuestionQuestionApiIdDeleteErrors];

export type DeleteQuestionQuestionsQuestionQuestionApiIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteQuestionQuestionsQuestionQuestionApiIdDeleteResponse = DeleteQuestionQuestionsQuestionQuestionApiIdDeleteResponses[keyof DeleteQuestionQuestionsQuestionQuestionApiIdDeleteResponses];

export type EditResponseResponsesResponseResponseApiIdEditResponsePostData = {
    body: ResponseCreateBase;
    path: {
        response_api_id: string;
    };
    query?: never;
    url: '/responses/response/{response_api_id}:edit_response';
};

export type EditResponseResponsesResponseResponseApiIdEditResponsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditResponseResponsesResponseResponseApiIdEditResponsePostError = EditResponseResponsesResponseResponseApiIdEditResponsePostErrors[keyof EditResponseResponsesResponseResponseApiIdEditResponsePostErrors];

export type EditResponseResponsesResponseResponseApiIdEditResponsePostResponses = {
    /**
     * Successful Response
     */
    200: ResponseLinked;
};

export type EditResponseResponsesResponseResponseApiIdEditResponsePostResponse = EditResponseResponsesResponseResponseApiIdEditResponsePostResponses[keyof EditResponseResponsesResponseResponseApiIdEditResponsePostResponses];

export type UploadImageResponsesResponseResponseApiIdUploadImagePostData = {
    body: BodyUploadImageResponsesResponseResponseApiIdUploadImagePost;
    path: {
        response_api_id: string;
    };
    query?: never;
    url: '/responses/response/{response_api_id}:upload_image';
};

export type UploadImageResponsesResponseResponseApiIdUploadImagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageResponsesResponseResponseApiIdUploadImagePostError = UploadImageResponsesResponseResponseApiIdUploadImagePostErrors[keyof UploadImageResponsesResponseResponseApiIdUploadImagePostErrors];

export type UploadImageResponsesResponseResponseApiIdUploadImagePostResponses = {
    /**
     * Successful Response
     */
    200: ResponseLinked;
};

export type UploadImageResponsesResponseResponseApiIdUploadImagePostResponse = UploadImageResponsesResponseResponseApiIdUploadImagePostResponses[keyof UploadImageResponsesResponseResponseApiIdUploadImagePostResponses];

export type CreateInviteInvitesPostData = {
    body: InviteCreate;
    path?: never;
    query?: never;
    url: '/invites/';
};

export type CreateInviteInvitesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteInvitesPostError = CreateInviteInvitesPostErrors[keyof CreateInviteInvitesPostErrors];

export type CreateInviteInvitesPostResponses = {
    /**
     * Successful Response
     */
    200: InviteLinked;
};

export type CreateInviteInvitesPostResponse = CreateInviteInvitesPostResponses[keyof CreateInviteInvitesPostResponses];

export type ValidateTokenInvitesTokenTokenGetData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/invites/token/{token}';
};

export type ValidateTokenInvitesTokenTokenGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateTokenInvitesTokenTokenGetError = ValidateTokenInvitesTokenTokenGetErrors[keyof ValidateTokenInvitesTokenTokenGetErrors];

export type ValidateTokenInvitesTokenTokenGetResponses = {
    /**
     * Successful Response
     */
    200: InviteLinked;
};

export type ValidateTokenInvitesTokenTokenGetResponse = ValidateTokenInvitesTokenTokenGetResponses[keyof ValidateTokenInvitesTokenTokenGetResponses];

export type PostSubscriptionNotificationsSubscriptionPostData = {
    body: SubscriptionCreate;
    path?: never;
    query?: never;
    url: '/notifications/subscription';
};

export type PostSubscriptionNotificationsSubscriptionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostSubscriptionNotificationsSubscriptionPostError = PostSubscriptionNotificationsSubscriptionPostErrors[keyof PostSubscriptionNotificationsSubscriptionPostErrors];

export type PostSubscriptionNotificationsSubscriptionPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type PostSubscriptionNotificationsSubscriptionPostResponse = PostSubscriptionNotificationsSubscriptionPostResponses[keyof PostSubscriptionNotificationsSubscriptionPostResponses];

export type GenerateCompletionLlmCompletionPostData = {
    body: CompletionRequest;
    path?: never;
    query?: never;
    url: '/llm/completion';
};

export type GenerateCompletionLlmCompletionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateCompletionLlmCompletionPostError = GenerateCompletionLlmCompletionPostErrors[keyof GenerateCompletionLlmCompletionPostErrors];

export type GenerateCompletionLlmCompletionPostResponses = {
    /**
     * Successful Response
     */
    200: CompletionResponse;
};

export type GenerateCompletionLlmCompletionPostResponse = GenerateCompletionLlmCompletionPostResponses[keyof GenerateCompletionLlmCompletionPostResponses];

export type RawSearchSearchSearchRawSearchGetData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        search_type?: SearchType;
        limit?: number;
    };
    url: '/search/search/raw-search';
};

export type RawSearchSearchSearchRawSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RawSearchSearchSearchRawSearchGetError = RawSearchSearchSearchRawSearchGetErrors[keyof RawSearchSearchSearchRawSearchGetErrors];

export type RawSearchSearchSearchRawSearchGetResponses = {
    /**
     * Successful Response
     */
    200: RawSearchResponse;
};

export type RawSearchSearchSearchRawSearchGetResponse = RawSearchSearchSearchRawSearchGetResponses[keyof RawSearchSearchSearchRawSearchGetResponses];

export type PerformSearchSearchSearchSearchGetData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        search_type?: SearchType;
        limit?: number;
    };
    url: '/search/search/search';
};

export type PerformSearchSearchSearchSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PerformSearchSearchSearchSearchGetError = PerformSearchSearchSearchSearchGetErrors[keyof PerformSearchSearchSearchSearchGetErrors];

export type PerformSearchSearchSearchSearchGetResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type PerformSearchSearchSearchSearchGetResponse = PerformSearchSearchSearchSearchGetResponses[keyof PerformSearchSearchSearchSearchGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type HelloHelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type HelloHelloGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HelloHelloGetResponse = HelloHelloGetResponses[keyof HelloHelloGetResponses];