name: Run Lint

on: [push]

jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: venv
      run: |
        uv sync --all-extras
        source .venv/bin/activate
    
    - name: Install project
      run: uv pip install -e .
    
    - name: Run lint
      run: uv run ring check lint
    