name: Run Unit Tests via pytest

on: [push]

jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Sync uv
      run: |
        uv sync --all-extras
        source .venv/bin/activate
    
    - name: Install project
      run: uv pip install -e .
    
    - name: Docker set-up
      run: |
        docker pull ghcr.io/neil-sriv/ring/ring-test-runner:latest
        uv run ring compose any --profile test pull
        docker network create ring-network
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: uv run ring test run
    