name: Run Unit Tests via pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Sync uv
      run: |
        uv sync --all-extras
        source .venv/bin/activate
    
    - name: Install project
      run: uv pip install -e .
    
    - name: Docker build
      run: ring compose any --profile test build

    - name: Run tests
      run: ring test run
    