# coding: utf-8

# flake8: noqa

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# import apis into sdk package
from llm_service.api.auth_api import AuthApi
from llm_service.api.completions_api import CompletionsApi
from llm_service.api.rag_api import RagApi

# import ApiClient
from llm_service.api_response import ApiResponse
from llm_service.api_client import ApiClient
from llm_service.configuration import Configuration
from llm_service.exceptions import OpenApiException
from llm_service.exceptions import ApiTypeError
from llm_service.exceptions import ApiValueError
from llm_service.exceptions import ApiKeyError
from llm_service.exceptions import ApiAttributeError
from llm_service.exceptions import ApiException

# import models into sdk package
from llm_service.models.completion_request import CompletionRequest
from llm_service.models.completion_response import CompletionResponse
from llm_service.models.http_validation_error import HTTPValidationError
from llm_service.models.rag_request import RAGRequest
from llm_service.models.rag_response import RAGResponse
from llm_service.models.validation_error import ValidationError
from llm_service.models.validation_error_loc_inner import (
    ValidationErrorLocInner,
)
